// You can find instructions for this file here:
// http://www.treeview.net

// Decide if the names are links or just the icons
USETEXTLINKS = 1  //replace 0 with 1 for hyperlinks

// Decide if the tree is to start all open or just showing the root folders
STARTALLOPEN = 0 //replace 0 with 1 to show the whole tree

ICONPATH = 'menu_files/' //change if the gif's folder is a subfolder, for example: 'images/'



foldersTree = gFld("<font size=3><b>Active Manuals</b></font>")
  Level1_Desc = insFld(foldersTree, gFld("Electrical Manuals"))
    Level2_Desc = insFld(Level1_Desc, gFld("I/O and Connections"))
      insDoc(Level2_Desc, gLnk("B", "I/O Unit Model A Connection and Maintenance", "../MARMGIOMA12801E_REV_C/book.pdf"))
      insDoc(Level2_Desc, gLnk("B", "I/O Unit Model B Connection and Maintenance", "../MARFIOUMB04701E_REV_B/toc.htm"))
    Level2_Desc = insFld(Level1_Desc, gFld("Motors and Amps"))
      insDoc(Level2_Desc, gLnk("B", "Alpha Series Servo Motor Maintenance", "../MARMALPSE01801E_REV_B/book.pdf"))
      insDoc(Level2_Desc, gLnk("B", "Alpha i Series Servo Amplifier Descriptions", "../MARD3SAAD05011E_REV_C/book.pdf"))
      insDoc(Level2_Desc, gLnk("B", "Alpha i Series Servo Motor Descriptions", "../MARDALPHS06011E_REV_A/book.pdf"))
      insDoc(Level2_Desc, gLnk("B", "Alpha i Series Servo Motor Maintenance ", "../MARMISMAI09011E_REV_A/book.pdf"))
      insDoc(Level2_Desc, gLnk("B", "Beta Series Servo Motor Descriptions", "../MARDBSRVM05021E_REV_A/book.pdf"))
    Level2_Desc = insFld(Level1_Desc, gFld("R-J Controller"))
      insDoc(Level2_Desc, gLnk("B", "Controller Maintenance", "../MARMMTRBL02303E_REV_A/book.pdf"))
    Level2_Desc = insFld(Level1_Desc, gFld("R-J2 Controller"))
      insDoc(Level2_Desc, gLnk("B", "Controller Parts", "../MARP2CONT01504E_REV_A/toc.htm"))
      insDoc(Level2_Desc, gLnk("B", "Electrical Troubleshooting", "../MARMMOSH205502E_REV_A/toc.htm"))
      insDoc(Level2_Desc, gLnk("B", "P-10, P-15, and P-200 Controller Maintenance", "../MARO2P10203704E_REV_B/book.pdf"))
      insDoc(Level2_Desc, gLnk("B", "RS-1 Controller Maintenance", "../MARE2RS1C04801E_REV_A/toc.htm"))
      insDoc(Level2_Desc, gLnk("B", "RS-1/RS-4 Option Maintenance Addendum", "../MARX2RELI09703E_REV_A/toc.htm"))
    Level2_Desc = insFld(Level1_Desc, gFld("R-J3 Controller"))
      insDoc(Level2_Desc, gLnk("B", "Auxiliary Axis", "../MARM3XAXS02001E_REV_A/toc.htm"))
      insDoc(Level2_Desc, gLnk("B", "Brake Release", "../MARAMBKRL06602E_REV_B/book.pdf"))
      insDoc(Level2_Desc, gLnk("B", "Controller Maintenance", "../MARM3CONM10801E_REV_E/toc.htm"))
      insDoc(Level2_Desc, gLnk("B", "Controller Parts", "../MARP3CNTP10801E_REV_C/toc.htm"))
      insDoc(Level2_Desc, gLnk("B", "I-21i Maintenance", "../MARM3I2L107901E_REV_B/book.pdf"))
      insDoc(Level2_Desc, gLnk("B", "RS-1/RS-4 Option Maintenance Addendum", "../MARX3RS4A06901E_REV_C/book.pdf"))
    Level2_Desc = insFld(Level1_Desc, gFld("R-J3 RIA Controller"))
      insDoc(Level2_Desc, gLnk("B", "Controller Maintenance", "../MARMRIAMT05001E_REV_B/book.pdf"))
      insDoc(Level2_Desc, gLnk("B", "Controller Parts", "../MARPRIAPT05001E_REV_A/toc.htm"))
      insDoc(Level2_Desc, gLnk("B", "HSI Pulse Module", "../MARO3HSIP12901E_REV_A/book.pdf"))
    Level2_Desc = insFld(Level1_Desc, gFld("R-J3iB Controller"))
      insDoc(Level2_Desc, gLnk("B", "Auxiliary Axis Connection and Maintenance", "../MAREIBAUX11011E_REV_B/book.pdf"))
      insDoc(Level2_Desc, gLnk("B", "Connection and Maintenance", "../MARMIBRIA03011E_REV_D/book.pdf"))
      insDoc(Level2_Desc, gLnk("B", "Controller Parts", "../MARPIBRIA04011E_REV_C/book.pdf"))
      insDoc(Level2_Desc, gLnk("B", "GM Maintenance Addendum", "MARXIBRIA10011E_REV_B/GM Maintenance Addendum"))
      insDoc(Level2_Desc, gLnk("B", "HSI Pulse Module", "../MARO3HSIP12901E_REV_B/book.pdf"))
      insDoc(Level2_Desc, gLnk("B", "Nobot Connection and Maintenance", "../MARMINOBT11011E_REV_A/book.pdf"))
      Level2_Desc = insFld(Level1_Desc, gFld("R-J3iB Mate Controller"))
      insDoc(Level2_Desc, gLnk("B", "Controller Maintenance", "../MARMIBRIA01021E_REV_A/book.pdf"))
      insDoc(Level2_Desc, gLnk("B", "Controller Parts", "../MARPIBRIA02021E_REV_A/book.pdf"))
      insDoc(Level2_Desc, gLnk("B", "Ethernet Connections and Maintenance Addendum", "../MARMIBENT02021E_REV_A/book.pdf"))
  Level1_Desc = insFld(foldersTree, gFld("Mechanical Manuals"))
    Level2_Desc = insFld(Level1_Desc, gFld("A-520i"))
      insDoc(Level2_Desc, gLnk("B", "Mechanical Unit Maintenance", "../MARM3A52I10801E_REV_A/toc.htm"))
      insDoc(Level2_Desc, gLnk("B", "Mechanical Unit Parts", "../MARP3A52010801E_REV_A/toc.htm"))
    Level2_Desc = insFld(Level1_Desc, gFld("ARC Mate 100i/M-6i"))
      insDoc(Level2_Desc, gLnk("B", "Mechanical Unit Maintenance", "../MARM3AMM609801E_REV_A/toc.htm"))
    Level2_Desc = insFld(Level1_Desc, gFld("ARC Mate 100iB/M-6iB"))
      insDoc(Level2_Desc, gLnk("B", "Mechanical Unit Maintenance", "../MARMIBARC11011E_REV_A/book.pdf"))
      insDoc(Level2_Desc, gLnk("B", "Mechanical Unit Parts", "../MARPIBARC11011E_REV_A/book.pdf"))
    Level2_Desc = insFld(Level1_Desc, gFld("ARC Mate 120i/iL & M-16i/iL"))
      insDoc(Level2_Desc, gLnk("B", "Mechanical Unit Maintenance", "../MARM3AR1609801E_REV_A/toc.htm"))
    Level2_Desc = insFld(Level1_Desc, gFld("ARC Mate 120i/iL/iLT & M-16i/iT/iLT"))
      insDoc(Level2_Desc, gLnk("B", "Mechanical Unit Parts", "../MARP3AR1609801E_REV_B/toc.htm"))
    Level2_Desc = insFld(Level1_Desc, gFld("ARC Mate 120iB, 120iB/10L, M-16iB/20, M-16iB/10L"))
      insDoc(Level2_Desc, gLnk("B", "Mechanical Unit Maintenance", "../MARMI120I07021E_REV_A/book.pdf"))
    Level2_Desc = insFld(Level1_Desc, gFld("ARC Mate Positioner"))
      insDoc(Level2_Desc, gLnk("B", "Parts and Service", "../MARM3FEWH03901E_REV_A/toc.htm"))
    Level2_Desc = insFld(Level1_Desc, gFld("F-200i"))
      insDoc(Level2_Desc, gLnk("B", "Mechanical Unit Maintenance", "../MARM3F20008901E_REV_A/toc.htm"))
      insDoc(Level2_Desc, gLnk("B", "Mechanical Unit Parts", "../MARP3F20007901E_REV_A/toc.htm"))
    Level2_Desc = insFld(Level1_Desc, gFld("F-200iB"))
      insDoc(Level2_Desc, gLnk("B", "Mechanical Unit Maintenance", "../MARMIF20004021E_REV_A/book.pdf"))
      insDoc(Level2_Desc, gLnk("B", "Mechanical Unit Parts", "../MARPIF20004021E_REV_A/book.pdf"))
    Level2_Desc = insFld(Level1_Desc, gFld("GM RS-1/RS-4 "))
      insDoc(Level2_Desc, gLnk("B", "R-J3 Mechanical Unit Installation", "../MARI3RS1407901E_REV_A/toc.htm"))
      insDoc(Level2_Desc, gLnk("B", "R-J3iB Mechanical Unit Installation", "../MARFIBRSM03021E_REV_A/book.pdf"))
    Level2_Desc = insFld(Level1_Desc, gFld("IAD"))
      insDoc(Level2_Desc, gLnk("B", "Parts and Service", "../MARQ3IADV01011E_REV_A/book.pdf"))
    Level2_Desc = insFld(Level1_Desc, gFld("LR Mate 100iB"))
      insDoc(Level2_Desc, gLnk("B", "Mechanical Unit Maintenance", "../MARMIBLRM12011E_REV_A/book.pdf"))
      insDoc(Level2_Desc, gLnk("B", "Mechanical Unit Parts", "../MARPLRM1I04021E_REV_A/book.pdf"))
    Level2_Desc = insFld(Level1_Desc, gFld("LR Mate 200i/iL & ARC Mate 50i/iL"))
      insDoc(Level2_Desc, gLnk("B", "Mechanical Unit Maintenance", "../MARM2LR2002901E_REV_B/toc.htm"))
      insDoc(Level2_Desc, gLnk("B", "Mechanical Unit Parts", "../MARP3LR2001011E_REV_A/book.pdf"))
    Level2_Desc = insFld(Level1_Desc, gFld("LR Mate 200iB/3L & ARC Mate 50iB/3L"))
      insDoc(Level2_Desc, gLnk("B", "Mechanical Unit Maintenance", "../MARMIBLR203021E_REV_A/book.pdf"))
      insDoc(Level2_Desc, gLnk("B", "Mechanical Unit Parts", "../MARPIM23L04021E_REV_A/book.pdf"))
    Level2_Desc = insFld(Level1_Desc, gFld("LR Mate 200iB/ARC Mate 50iB"))
      insDoc(Level2_Desc, gLnk("B", "Mechanical Unit Parts", "../MARPLRM2I04021E_REV_A/book.pdf"))
    Level2_Desc = insFld(Level1_Desc, gFld("M-410iHS/HW"))
      insDoc(Level2_Desc, gLnk("B", "Mechanical Unit Maintenance", "../MARM3M41009801E_REV_A/toc.htm"))
      insDoc(Level2_Desc, gLnk("B", "Mechanical Unit Parts", "../MARP3M41009801E_REV_A/toc.htm"))
    Level2_Desc = insFld(Level1_Desc, gFld("M-420iA & M-421iA"))
      insDoc(Level2_Desc, gLnk("B", "Mechanical Unit Maintenance", "../MARMIB42A04021E_REV_A/book.pdf"))
      insDoc(Level2_Desc, gLnk("B", "Mechanical Unit Parts", "../MARMI42IA04021E_REV_A/book.pdf"))
    Level2_Desc = insFld(Level1_Desc, gFld("M-500i"))
      insDoc(Level2_Desc, gLnk("B", "Mechanical Unit Maintenance", "../MARM3M50007901E_REV_A/toc.htm"))
      insDoc(Level2_Desc, gLnk("B", "Mechanical Unit Parts", "../MARP3M50007901E_REV_A/toc.htm"))
    Level2_Desc = insFld(Level1_Desc, gFld("M-6i to P-90"))
      insDoc(Level2_Desc, gLnk("B", "Conversion", "../MARX3M6IC08011E_REV_A/book.pdf"))
    Level2_Desc = insFld(Level1_Desc, gFld("M-6i/iT & ARC Mate 100i/iT "))
      insDoc(Level2_Desc, gLnk("B", "Mechanical Unit Parts ", "../MARP3AMM609801E_REV_B/toc.htm"))
    Level2_Desc = insFld(Level1_Desc, gFld("M-6iT, M-16iT, M-16iLT"))
      insDoc(Level2_Desc, gLnk("B", "Installation", "../MARF3M6IT03901E_REV_B/toc.htm"))
      insDoc(Level2_Desc, gLnk("B", "Parts and Service", "../MARP3M6IT04901E_REV_C/toc.htm"))
    Level2_Desc = insFld(Level1_Desc, gFld("M-710i"))
      insDoc(Level2_Desc, gLnk("B", "Mechanical Unit Maintenance", "../MARM3710I09801E_REV_B/toc.htm"))
      insDoc(Level2_Desc, gLnk("B", "Mechanical Unit Parts", "../MARP3M71009801E_REV_A/toc.htm"))
    Level2_Desc = insFld(Level1_Desc, gFld("M-710iB/45/45E"))
      insDoc(Level2_Desc, gLnk("B", "Mechanical Unit Maintenance", "../MARMI710I03021E_REV_A/book.pdf"))
      insDoc(Level2_Desc, gLnk("B", "Mechanical Unit Parts", "../MARPI710I0302E_REV_A/book.pdf"))
    Level2_Desc = insFld(Level1_Desc, gFld("M-710iB/70"))
      insDoc(Level2_Desc, gLnk("B", "Mechanical Unit Maintenance", "../MARMIM71708021E_REV_A/book.pdf"))
      insDoc(Level2_Desc, gLnk("B", "Mechanical Unit Parts", "../MARPIM71708021E_REV_A/book.pdf"))
    Level2_Desc = insFld(Level1_Desc, gFld("M-710iT"))
      insDoc(Level2_Desc, gLnk("B", "Carriage, Rail and Column Parts and Service", "../MARP3710T02001E_REV_B/toc.htm"))
      insDoc(Level2_Desc, gLnk("B", "Mechanical Unit Maintenance", "../MARM3710P12901E_REV_A/toc.htm"))
      insDoc(Level2_Desc, gLnk("B", "Mechanical Unit Parts", "../MARP3710P12901E_REV_A/toc.htm"))
    Level2_Desc = insFld(Level1_Desc, gFld("M-710iW"))
      insDoc(Level2_Desc, gLnk("B", "Mechanical Unit Maintenance", "../MARM3M71010801E_REV_B/toc.htm"))
      insDoc(Level2_Desc, gLnk("B", "Mechanical Unit Parts", "../MARP3M71W11801E_REV_A/toc.htm"))
    Level2_Desc = insFld(Level1_Desc, gFld("P-10 & P-15 Openers"))
      insDoc(Level2_Desc, gLnk("B", "Parts and Service", "../MARP2P15S10701E_REV_A/book.pdf"))
    Level2_Desc = insFld(Level1_Desc, gFld("P-10E & P-15E Openers"))
      insDoc(Level2_Desc, gLnk("B", "Parts and Service", "../MARP3P15S11011E_REV_A/book.pdf"))
    Level2_Desc = insFld(Level1_Desc, gFld("P-120"))
      insDoc(Level2_Desc, gLnk("B", "Parts and Service", "../MARP3P12007801E_REV_A/toc.htm"))
    Level2_Desc = insFld(Level1_Desc, gFld("P-145"))
      insDoc(Level2_Desc, gLnk("B", "Parts and Service", "../MARP3P14507801E_REV_B/toc.htm"))
    Level2_Desc = insFld(Level1_Desc, gFld("P-155"))
      insDoc(Level2_Desc, gLnk("B", "Mechanical Unit Parts", "../MARPMP15506204E_REV_B/book.pdf"))
      insDoc(Level2_Desc, gLnk("B", "Mechanical Unit Service", "../MARRPP15506204E_REV_B/book.pdf"))
    Level2_Desc = insFld(Level1_Desc, gFld("P-200 Pedestal and In-Booth Rail"))
      insDoc(Level2_Desc, gLnk("B", "Parts and Service", "../MARP2P20007604E_REV_A/book.pdf"))
    Level2_Desc = insFld(Level1_Desc, gFld("P-200 Pedestal, In Booth Rail, & Clean Wall Rail  "))
      insDoc(Level2_Desc, gLnk("B", "Parts and Service", "../MARP3P2CW01901E_REV_B/toc.htm"))
    Level2_Desc = insFld(Level1_Desc, gFld("P-200E Pedestal, Clean Wall Rail, In-booth Rail"))
      insDoc(Level2_Desc, gLnk("B", "Parts and Service", "../MARP3200E06011E_REV_B/book.pdf"))
    Level2_Desc = insFld(Level1_Desc, gFld("R-2000iA"))
      insDoc(Level2_Desc, gLnk("B", "Mechanical Unit Maintenance", "../MARMIBR2I03011E_REV_C/book.pdf"))
      insDoc(Level2_Desc, gLnk("B", "Mechanical Unit Parts", "../MARPIBR2I03011E_REV_C/book.pdf"))
    Level2_Desc = insFld(Level1_Desc, gFld("R-2000iA/200T"))
      insDoc(Level2_Desc, gLnk("B", "Mechanical Unit Maintenance", "../MARMI2IAT0702IE_REV_A/book.pdf"))
      insDoc(Level2_Desc, gLnk("B", "Mechanical Unit Parts", "../MARPI2IAT08021E_REV_A/book.pdf"))
    Level2_Desc = insFld(Level1_Desc, gFld("Robot Transfer Unit"))
      insDoc(Level2_Desc, gLnk("B", "Mechanical Parts and Service", "../MARP3RTU010211E_REV_A/book.pdf"))
    Level2_Desc = insFld(Level1_Desc, gFld("S-420i Series"))
      insDoc(Level2_Desc, gLnk("B", "Mechanical Service", "../MARRS42IF05502E_REV_A/toc.htm"))
    Level2_Desc = insFld(Level1_Desc, gFld("S-420iF/W/S/L/R"))
      insDoc(Level2_Desc, gLnk("B", "Mechanical Unit Parts", "../MARP2420I02801E_REV_B/book.pdf"))
    Level2_Desc = insFld(Level1_Desc, gFld("S-430i"))
      insDoc(Level2_Desc, gLnk("B", "Mechanical Unit Maintenance", "../MARM3S43009801E_REV_D/toc.htm"))
      insDoc(Level2_Desc, gLnk("B", "Mechanical Unit Parts", "../MARP3S43009801E_REV_B/toc.htm"))
    Level2_Desc = insFld(Level1_Desc, gFld("S-430i Series GM RS-1 "))
      insDoc(Level2_Desc, gLnk("B", "Mechanical Unit Maintenance", "../MARM3GMS408901E_REV_C/book.pdf"))
    Level2_Desc = insFld(Level1_Desc, gFld("S-500i"))
      insDoc(Level2_Desc, gLnk("B", "Mechanical Unit Maintenance", "../MARM3S50007901E_REV_A/toc.htm"))
      insDoc(Level2_Desc, gLnk("B", "Mechanical Unit Parts", "../MARP3S50001001E_REV_A/toc.htm"))
    Level2_Desc = insFld(Level1_Desc, gFld("S-900i"))
      insDoc(Level2_Desc, gLnk("B", "Mechanical Unit Maintenance", "../MARM3S90008901E_REV_A/toc.htm"))
      insDoc(Level2_Desc, gLnk("B", "Mechanical Unit Parts", "../MARP3S90008901E_REV_A/toc.htm"))
    Level2_Desc = insFld(Level1_Desc, gFld("S-900iB"))
      insDoc(Level2_Desc, gLnk("B", "Mechanical Unit Maintenance", "../MARMIBS9007021E_REV_A/book.pdf"))
      insDoc(Level2_Desc, gLnk("B", "Mechanical Unit Parts", "../MARPIS90007021E_REV_A/book.pdf"))
    Level2_Desc = insFld(Level1_Desc, gFld("ServoBell Applicator"))
      insDoc(Level2_Desc, gLnk("B", "Parts and Service", "../MARPGWBBL02021E_REV_A/book.pdf"))
      Level2_Desc = insFld(Level1_Desc, gFld("VersaBell Atomizer"))
      insDoc(Level2_Desc, gLnk("B", "Parts and Service", "../MARPGBELL12011E_REV_B/book.pdf"))
    Level2_Desc = insFld(Level1_Desc, gFld("R-J3iB"))
      Level3_Desc = insFld(Level2_Desc, gFld("A-520i"))
        insDoc(Level3_Desc, gLnk("B", "Mechanical Unit Maintenance", "MARM3A52I10801E_REV_A/"))
        insDoc(Level3_Desc, gLnk("B", "Mechanical Unit Parts", "MARP3A52010801E_REV_A/"))
      Level3_Desc = insFld(Level2_Desc, gFld("ARC Mate 100i/M-6i"))
        insDoc(Level3_Desc, gLnk("B", "Mechanical Unit Maintenance", "MARM3AMM609801E_REV_A/"))
      Level3_Desc = insFld(Level2_Desc, gFld("ARC Mate 100iB/M-6iB"))
        insDoc(Level3_Desc, gLnk("B", "Mechanical Unit Maintenance", "MARMIBARC11011E_REV_A/"))
        insDoc(Level3_Desc, gLnk("B", "Mechanical Unit Parts", "MARPIBARC11011E_REV_A/"))
      Level3_Desc = insFld(Level2_Desc, gFld("ARC Mate 120i/iL & M-16i/iL"))
        insDoc(Level3_Desc, gLnk("B", "Mechanical Unit Maintenance", "MARM3AR1609801E_REV_A/"))
      Level3_Desc = insFld(Level2_Desc, gFld("ARC Mate 120i/iL/iLT & M-16i/iT/iLT"))
        insDoc(Level3_Desc, gLnk("B", "Mechanical Unit Parts", "MARP3AR1609801E_REV_B/"))
      Level3_Desc = insFld(Level2_Desc, gFld("ARC Mate 120iB, 120iB/10L, M-16iB/20, M-16iB/10L"))
        insDoc(Level3_Desc, gLnk("B", "Mechanical Unit Maintenance", "MARMI120I07021E_REV_A/"))
      Level3_Desc = insFld(Level2_Desc, gFld("ARC Mate Positioner"))
        insDoc(Level3_Desc, gLnk("B", "Parts and Service", "MARM3FEWH03901E_REV_A/"))
      Level3_Desc = insFld(Level2_Desc, gFld("F-200i"))
        insDoc(Level3_Desc, gLnk("B", "Mechanical Unit Maintenance", "MARM3F20008901E_REV_A/"))
        insDoc(Level3_Desc, gLnk("B", "Mechanical Unit Parts", "MARP3F20007901E_REV_A/"))
      Level3_Desc = insFld(Level2_Desc, gFld("F-200iB"))
        insDoc(Level3_Desc, gLnk("B", "Mechanical Unit Maintenance", "MARMIF20004021E_REV_A/"))
        insDoc(Level3_Desc, gLnk("B", "Mechanical Unit Parts", "MARPIF20004021E_REV_A/"))
      Level3_Desc = insFld(Level2_Desc, gFld("GM RS-1/RS-4 "))
        insDoc(Level3_Desc, gLnk("B", "R-J3 Mechanical Unit Installation", "MARI3RS1407901E_REV_A/"))
        insDoc(Level3_Desc, gLnk("B", "R-J3iB Mechanical Unit Installation", "MARFIBRSM03021E_REV_A/"))
      Level3_Desc = insFld(Level2_Desc, gFld("IAD"))
        insDoc(Level3_Desc, gLnk("B", "Parts and Service", "MARQ3IADV01011E_REV_A/"))
      Level3_Desc = insFld(Level2_Desc, gFld("LR Mate 100iB"))
        insDoc(Level3_Desc, gLnk("B", "Mechanical Unit Maintenance", "MARMIBLRM12011E_REV_A/"))
        insDoc(Level3_Desc, gLnk("B", "Mechanical Unit Parts", "MARPLRM1I04021E_REV_A/"))
      Level3_Desc = insFld(Level2_Desc, gFld("LR Mate 200i/iL & ARC Mate 50i/iL"))
        insDoc(Level3_Desc, gLnk("B", "Mechanical Unit Maintenance", "MARM2LR2002901E_REV_B/"))
        insDoc(Level3_Desc, gLnk("B", "Mechanical Unit Parts", "MARP3LR2001011E_REV_A/"))
      Level3_Desc = insFld(Level2_Desc, gFld("LR Mate 200iB/3L & ARC Mate 50iB/3L"))
        insDoc(Level3_Desc, gLnk("B", "Mechanical Unit Maintenance", "MARMIBLR203021E_REV_A/"))
        insDoc(Level3_Desc, gLnk("B", "Mechanical Unit Parts", "MARPIM23L04021E_REV_A/"))
      Level3_Desc = insFld(Level2_Desc, gFld("LR Mate 200iB/ARC Mate 50iB"))
        insDoc(Level3_Desc, gLnk("B", "Mechanical Unit Parts", "MARPLRM2I04021E_REV_A/"))
      Level3_Desc = insFld(Level2_Desc, gFld("M-410iHS/HW"))
        insDoc(Level3_Desc, gLnk("B", "Mechanical Unit Maintenance", "MARM3M41009801E_REV_A/"))
        insDoc(Level3_Desc, gLnk("B", "Mechanical Unit Parts", "MARP3M41009801E_REV_A/"))
      Level3_Desc = insFld(Level2_Desc, gFld("M-420iA & M-421iA"))
        insDoc(Level3_Desc, gLnk("B", "Mechanical Unit Maintenance", "MARMIB42A04021E_REV_A/"))
        insDoc(Level3_Desc, gLnk("B", "Mechanical Unit Parts", "MARMI42IA04021E_REV_A/"))
      Level3_Desc = insFld(Level2_Desc, gFld("M-500i"))
        insDoc(Level3_Desc, gLnk("B", "Mechanical Unit Maintenance", "MARM3M50007901E_REV_A/"))
        insDoc(Level3_Desc, gLnk("B", "Mechanical Unit Parts", "MARP3M50007901E_REV_A/"))
      Level3_Desc = insFld(Level2_Desc, gFld("M-6i to P-90"))
        insDoc(Level3_Desc, gLnk("B", "Conversion", "MARX3M6IC08011E_REV_A/"))
      Level3_Desc = insFld(Level2_Desc, gFld("M-6i/iT & ARC Mate 100i/iT "))
        insDoc(Level3_Desc, gLnk("B", "Mechanical Unit Parts ", "MARP3AMM609801E_REV_B/"))
      Level3_Desc = insFld(Level2_Desc, gFld("M-6iT, M-16iT, M-16iLT"))
        insDoc(Level3_Desc, gLnk("B", "Installation", "MARF3M6IT03901E_REV_B/"))
        insDoc(Level3_Desc, gLnk("B", "Parts and Service", "MARP3M6IT04901E_REV_C/"))
      Level3_Desc = insFld(Level2_Desc, gFld("M-710i"))
        insDoc(Level3_Desc, gLnk("B", "Mechanical Unit Maintenance", "MARM3710I09801E_REV_B/"))
        insDoc(Level3_Desc, gLnk("B", "Mechanical Unit Parts", "MARP3M71009801E_REV_A/"))
      Level3_Desc = insFld(Level2_Desc, gFld("M-710iB/45/45E"))
        insDoc(Level3_Desc, gLnk("B", "Mechanical Unit Maintenance", "MARMI710I03021E_REV_A/"))
        insDoc(Level3_Desc, gLnk("B", "Mechanical Unit Parts", "MARPI710I0302E _REV_A/"))
      Level3_Desc = insFld(Level2_Desc, gFld("M-710iT"))
        insDoc(Level3_Desc, gLnk("B", "Carriage, Rail and Column Parts and Service", "MARP3710T02001E_REV_B/"))
        insDoc(Level3_Desc, gLnk("B", "Installation", "MARF3710T02001E_REV_A/"))
        insDoc(Level3_Desc, gLnk("B", "Mechanical Unit Maintenance", "MARM3710P12901E_REV_A/"))
        insDoc(Level3_Desc, gLnk("B", "Mechanical Unit Parts", "MARP3710P12901E_REV_A/"))
      Level3_Desc = insFld(Level2_Desc, gFld("M-710iW"))
        insDoc(Level3_Desc, gLnk("B", "Mechanical Unit Maintenance", "MARM3M71010801E_REV_B/"))
        insDoc(Level3_Desc, gLnk("B", "Mechanical Unit Parts", "MARP3M71W11801E_REV_A/"))
      Level3_Desc = insFld(Level2_Desc, gFld("P-10E & P-15E Openers"))
        insDoc(Level3_Desc, gLnk("B", "Parts and Service", "MARP3P15S11011E_REV_A/"))
      Level3_Desc = insFld(Level2_Desc, gFld("P-120"))
        insDoc(Level3_Desc, gLnk("B", "Parts and Service", "MARP3P12007801E_REV_A/"))
      Level3_Desc = insFld(Level2_Desc, gFld("P-145"))
        insDoc(Level3_Desc, gLnk("B", "Parts and Service", "MARP3P14507801E_REV_B/"))
      Level3_Desc = insFld(Level2_Desc, gFld("P-200 Pedestal, In Booth Rail, & Clean Wall Rail  "))
        insDoc(Level3_Desc, gLnk("B", "Parts and Service", "MARP3P2CW01901E_REV_B/"))
      Level3_Desc = insFld(Level2_Desc, gFld("P-200E Pedestal, Clean Wall Rail, In-booth Rail"))
        insDoc(Level3_Desc, gLnk("B", "Parts and Service", "MARP3200E06011E_REV_A/"))
      Level3_Desc = insFld(Level2_Desc, gFld("R-2000iA"))
        insDoc(Level3_Desc, gLnk("B", "Mechanical Unit Maintenance", "MARMIBR2I03011E_REV_C/"))
        insDoc(Level3_Desc, gLnk("B", "Mechanical Unit Parts", "MARPIBR2I03011E_REV_C/"))
      Level3_Desc = insFld(Level2_Desc, gFld("R-2000iA/200T"))
        insDoc(Level3_Desc, gLnk("B", "Mechanical Unit Maintenance", "MARMI2IAT0702IE_REV_A/"))
        insDoc(Level3_Desc, gLnk("B", "Mechanical Unit Parts", "MARPI2IAT08021E_REV_A/"))
      Level3_Desc = insFld(Level2_Desc, gFld("Robot Transfer Unit"))
        insDoc(Level3_Desc, gLnk("B", "Mechanical Parts and Service", "MARP3RTU010211E_REV_A/"))
      Level3_Desc = insFld(Level2_Desc, gFld("S-420i Series"))
        insDoc(Level3_Desc, gLnk("B", "Mechanical Service", "MARRS42IF05502E_REV_A/"))
        insDoc(Level3_Desc, gLnk("B", "Mechanical Unit Maintenance", "MARM2RS1408801E_REV_A/"))
        insDoc(Level3_Desc, gLnk("B", "Mechanical Unit Parts", "MARP2420I02801E_REV_A/"))
      Level3_Desc = insFld(Level2_Desc, gFld("S-420iF/W/S/L/R"))
        insDoc(Level3_Desc, gLnk("B", "Mechanical Unit Maintenance", "MARAMS42I08405E_REV_A/"))
        insDoc(Level3_Desc, gLnk("B", "Mechanical Unit Parts", "MARP2420I02801E_REV_B/"))
      Level3_Desc = insFld(Level2_Desc, gFld("S-430i"))
        insDoc(Level3_Desc, gLnk("B", "Mechanical Unit Maintenance", "MARM3S43009801E_REV_D/"))
        insDoc(Level3_Desc, gLnk("B", "Mechanical Unit Parts", "MARP3S43009801E_REV_B/"))
      Level3_Desc = insFld(Level2_Desc, gFld("S-430i Series GM RS-1 "))
        insDoc(Level3_Desc, gLnk("B", "Mechanical Unit Maintenance", "MARM3GMS408901E_REV_C/"))
      Level3_Desc = insFld(Level2_Desc, gFld("S-500i"))
        insDoc(Level3_Desc, gLnk("B", "Mechanical Unit Maintenance", "MARM3S50007901E_REV_A/"))
        insDoc(Level3_Desc, gLnk("B", "Mechanical Unit Parts", "MARP3S50001001E_REV_A/"))
      Level3_Desc = insFld(Level2_Desc, gFld("S-900i"))
        insDoc(Level3_Desc, gLnk("B", "Mechanical Unit Maintenance", "MARM3S90008901E_REV_A/"))
        insDoc(Level3_Desc, gLnk("B", "Mechanical Unit Parts", "MARP3S90008901E_REV_A/"))
      Level3_Desc = insFld(Level2_Desc, gFld("S-900iB"))
        insDoc(Level3_Desc, gLnk("B", "Mechanical Unit Maintenance", "MARMIBS9007021E_REV_A/"))
        insDoc(Level3_Desc, gLnk("B", "Mechanical Unit Parts", "MARPIS90007021E_REV_A/"))
      Level3_Desc = insFld(Level2_Desc, gFld("ServoBell Applicator"))
        insDoc(Level3_Desc, gLnk("B", "Parts and Service", "MARPGWBBL02021E_REV_A/"))
      Level3_Desc = insFld(Level2_Desc, gFld("VersaBell Atomizer"))
        insDoc(Level3_Desc, gLnk("B", "Parts and Service", "MARPGBELL12011E_REV_B/"))
  Level1_Desc = insFld(foldersTree, gFld("Software Manuals"))
    Level2_Desc = insFld(Level1_Desc, gFld("5.21P/D4"))
      Level3_Desc = insFld(Level2_Desc, gFld("Operations"))
        insDoc(Level3_Desc, gLnk("B", "YAG LaserTool Operations", "../MARO3LYAG04011E_REV_B/book.pdf"))
    Level2_Desc = insFld(Level1_Desc, gFld("M4.10"))
      Level3_Desc = insFld(Level2_Desc, gFld("Operations"))
        insDoc(Level3_Desc, gLnk("B", "LR TOOL Setup and Operations", "../MARO2LRTL05701E _REV_A/toc.htm"))
        insDoc(Level3_Desc, gLnk("B", "YAG LaserTool Operations", "../MARO3LYAG04011E_REV_B/book.pdf"))
    Level2_Desc = insFld(Level1_Desc, gFld("V4.30"))
      Level3_Desc = insFld(Level2_Desc, gFld("Options"))
        insDoc(Level3_Desc, gLnk("B", "V-400 Vision System Setup and Operations", "../MARO2VS4302701E_REV_A/toc.htm"))
    Level2_Desc = insFld(Level1_Desc, gFld("V5.11"))
      Level3_Desc = insFld(Level2_Desc, gFld("Communications and Network I/O"))
        insDoc(Level3_Desc, gLnk("B", "Cimplicity HMI Operator  ", "../MAROIBHMI09011E_REV_A/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "DeviceNet Interface User Guide", "../MARO3DN5110801E_REV_A/toc.htm"))
        insDoc(Level3_Desc, gLnk("B", "Ethernet Controller Backup and Restore-FTP", "../MARO3ET5110801E_REV_A/toc.htm"))
        insDoc(Level3_Desc, gLnk("B", "Remote I/O Interface for an Allen-Bradley PCL ", "../MARU3AB5109801E_REV_A/toc.htm"))
      Level3_Desc = insFld(Level2_Desc, gFld("Operations"))
        insDoc(Level3_Desc, gLnk("B", "ArcTool Setup and Operations", "../MARO3AT5109801E_REV_B/toc.htm"))
        insDoc(Level3_Desc, gLnk("B", "ArcTool Software Installation", "../MARF3AR5109801E_REV_A/toc.htm"))
        insDoc(Level3_Desc, gLnk("B", "HandlingTool Setup and Operations", "../MARO3HT5109801E_REV_B/toc.htm"))
        insDoc(Level3_Desc, gLnk("B", "HandlingTool Software Installation", "../MARF3HD5109801E_REV_A/toc.htm"))
        insDoc(Level3_Desc, gLnk("B", "PaintTool Setup and Operations", "../MARO3PT5109801E_REV_B/toc.htm"))
        insDoc(Level3_Desc, gLnk("B", "PaintTool Software Installation", "../MARF3PI5109801E_REV_B/toc.htm"))
        insDoc(Level3_Desc, gLnk("B", "PalletTool Software Installation", "../MARO3PL5109801E_REV_B/toc.htm"))
        insDoc(Level3_Desc, gLnk("B", "SpotTool+ Setup and Operations", "../MARO3ST5109801E_REV_A/toc.htm"))
        insDoc(Level3_Desc, gLnk("B", "SpotTool+ Software Installation", "../MARS35GEN09801E_REV_B/toc.htm"))
      Level3_Desc = insFld(Level2_Desc, gFld("Options"))
        insDoc(Level3_Desc, gLnk("B", "Accustat Maintenance", "../MARA3ACCU11001E_REV_A/toc.htm"))
        insDoc(Level3_Desc, gLnk("B", "Accustat Setup, Operations, and Maintenance", "../MARA3ACST10901E_REV_B/toc.htm"))
        insDoc(Level3_Desc, gLnk("B", "AssistTool Setup and Operations", "../MARO3ASTL01011E_REV_A/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Coordinated Motion Setup and Operations", "../MARO3CM5109801E_REV_A/toc.htm"))
        insDoc(Level3_Desc, gLnk("B", "KAREL and TPP Program Diagnostic Option", "../MARA3KT5111801E_REV_A/toc.htm"))
        insDoc(Level3_Desc, gLnk("B", "Linetracking Setup and Operations", "../MARO3LT5111801E_REV_A/toc.htm"))
        insDoc(Level3_Desc, gLnk("B", "TorchMate Setup and Operations", "../MARO3TM5109801E_REV_A/toc.htm"))
      Level3_Desc = insFld(Level2_Desc, gFld("Reference"))
        insDoc(Level3_Desc, gLnk("B", "KAREL Reference", "../MARS3KA5109801E_REV_B/toc.htm"))
        insDoc(Level3_Desc, gLnk("B", "R-J2 to R-J3 Compatibility Overview", "../MARO3COMP10801E_REV_A/toc.htm"))
        insDoc(Level3_Desc, gLnk("B", "Software Reference", "../MARS35GEN09801E_REV_B/toc.htm"))
    Level2_Desc = insFld(Level1_Desc, gFld("V5.20"))
      Level3_Desc = insFld(Level2_Desc, gFld("Communications and Network I/O"))
        insDoc(Level3_Desc, gLnk("B", "Cimplicity HMI Operator  ", "../MAROIBHMI09011E_REV_A/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "DeviceNet Setup & Operations", "../MARU3DNI510901E_REV_A/toc.htm"))
        insDoc(Level3_Desc, gLnk("B", "Ethernet Options", "../MARO3EFTP10901E_REV_A/toc.htm"))
        insDoc(Level3_Desc, gLnk("B", "Genius Network Interface for GE Fanuc User Guide ", "../MARUIBGNI05011E_REV_A/toc.htm"))
        insDoc(Level3_Desc, gLnk("B", "Remote I/O Interface for an Allen-Bradley PLC User guide", "../MARU3ABIO10901E_REV_B/toc.htm"))
      Level3_Desc = insFld(Level2_Desc, gFld("Operations"))
        insDoc(Level3_Desc, gLnk("B", "ArcTool Setup and Operations", "../MARO3AT5208901E_REV_C/toc.htm"))
        insDoc(Level3_Desc, gLnk("B", "DispenseTool Plug-in to SpotTool+ Setup and Operations", "../MARO3DPST07901E_REV_A/toc.htm"))
        insDoc(Level3_Desc, gLnk("B", "DispenseTool Setup and Operations", "../MARO3DT5207901E_REV_C/toc.htm"))
        insDoc(Level3_Desc, gLnk("B", "HandlingTool Setup and Operations", "../MARO3HA5208901E_REV_B/toc.htm"))
        insDoc(Level3_Desc, gLnk("B", "PaintTool Setup and Operations", "../MARO3PN5208901E_REV_C/toc.htm"))
        insDoc(Level3_Desc, gLnk("B", "PalletTool Setup and Operations", "../MARO3PTHT10901E_REV_C/toc.htm"))
        insDoc(Level3_Desc, gLnk("B", "RemovalTool Setup and Operations", "../MARO3RT5210901E_REV_A/toc.htm"))
        insDoc(Level3_Desc, gLnk("B", "Software Installation", "../MARF3GN5208901E_REV_C/toc.htm"))
        insDoc(Level3_Desc, gLnk("B", "SpotTool+ Setup and Operations", "../MARO3ST5202901E_REV_C/toc.htm"))
      Level3_Desc = insFld(Level2_Desc, gFld("Options"))
        insDoc(Level3_Desc, gLnk("B", "Accustat Maintenance", "../MARA3ACCU11001E_REV_A/toc.htm"))
        insDoc(Level3_Desc, gLnk("B", "AssistTool Setup and Operations", "../MARO3ASTL01011E_REV_A/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Continuous Turn User Guide", "../MARU3CT5111801E_REV_B/toc.htm"))
        insDoc(Level3_Desc, gLnk("B", "Coordinated Motion Setup and Operations  ", "../MAROIBCM605011E_REV_A/toc.htm"))
        insDoc(Level3_Desc, gLnk("B", "HSI Pulse Module", "../MARO3HSIP12901E_REV_A/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Linetracking Setup and Operations", "../MARO3LT5210901E_REV_A/toc.htm"))
      Level3_Desc = insFld(Level2_Desc, gFld("Reference"))
        insDoc(Level3_Desc, gLnk("B", "Accustat Maintenance", "../MARA3ACCU11001E_REV_A/toc.htm"))
        insDoc(Level3_Desc, gLnk("B", "Error Code", "../MARA3ERCD11001E_REV_A/toc.htm"))
        insDoc(Level3_Desc, gLnk("B", "KAREL and TPP Program Diagnostic Option", "../MARA3KLTP05001E_REV_B/toc.htm"))
        insDoc(Level3_Desc, gLnk("B", "Software Reference", "MCRA3KR5211901E_REV_A/toc.htm"))
    Level2_Desc = insFld(Level1_Desc, gFld("V5.22"))
      Level3_Desc = insFld(Level2_Desc, gFld("Communications and Network I/O"))
        insDoc(Level3_Desc, gLnk("B", "Cimplicity HMI Operator  ", "../MAROIBHMI09011E_REV_A/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "ControlNet Interface User Guide", "../MARU3CN5203001E_REV_A/toc.htm"))
        insDoc(Level3_Desc, gLnk("B", "DeviceNet Setup and Operations", "../MARO3DENT05001E_REV_B/toc.htm"))
        insDoc(Level3_Desc, gLnk("B", "Genius Network Interface for GE Fanuc User Guide ", "../MARUIBGNI05011E_REV_A/toc.htm"))
        insDoc(Level3_Desc, gLnk("B", "HMI User Guide", "../MARUIBHMI05011E_REV_A/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Internet Options Setup and Operations", "../MARO3IO5203001E_REV_A/toc.htm"))
        insDoc(Level3_Desc, gLnk("B", "PROFIBUS-DP (12M) Interface Function Operator  ", "../MARAIBPRO05011E_REV_A/toc.htm"))
        insDoc(Level3_Desc, gLnk("B", "Remote I/O Interface for an Allen-Bradley PLC User Guide ", "../MARUIBABI05011E_REV_A/toc.htm"))
        insDoc(Level3_Desc, gLnk("B", "Remote I/O Interface for an Allen-Bradley PLC User guide", "../MARU3ABIO10901E_REV_B/toc.htm"))
      Level3_Desc = insFld(Level2_Desc, gFld("Operations"))
        insDoc(Level3_Desc, gLnk("B", "DispenseTool Plug-in to SpotTool+ Setup and Operations", "../MARO3DTSP04001E_REV_A/toc.htm"))
        insDoc(Level3_Desc, gLnk("B", "HandlingTool Setup and Operations", "../MARO3H52204001E_REV_C/toc.htm"))
        insDoc(Level3_Desc, gLnk("B", "Internet Options Setup and Operations", "MAROIBINT04011E_REV_A/default.htm"))
        insDoc(Level3_Desc, gLnk("B", "PalletTool Setup and Operations", "../MARO3PTHT10901E_REV_C/toc.htm"))
        insDoc(Level3_Desc, gLnk("B", "RemovalTool Setup and Operations", "../MARO3RT5210901E_REV_B/toc.htm"))
        insDoc(Level3_Desc, gLnk("B", "Software Installation", "../MARF3V52204001E_REV_A/toc.htm"))
        insDoc(Level3_Desc, gLnk("B", "SpotTool+ Setup and Operations", "../MARO3SPOT04001E_REV_C/toc.htm"))
      Level3_Desc = insFld(Level2_Desc, gFld("Options"))
        insDoc(Level3_Desc, gLnk("B", "Continuous Turn User Guide", "../MARU3CT5111801E_REV_B/toc.htm"))
        insDoc(Level3_Desc, gLnk("B", "Coordinated Motion Setup and Operations  ", "../MAROIBCM605011E_REV_A/toc.htm"))
        insDoc(Level3_Desc, gLnk("B", "FAPT Ladder-III Operator ", "../MAROFAPT05011E_REV_B/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Integrated PMC Operator", "../MARX3PMC011001E_REV_B/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Integrated Welding Control Interface User Guide", "../MARO3IS5101901E_REV_B/toc.htm"))
        insDoc(Level3_Desc, gLnk("B", "Internet Options Setup and Operations", "MAROIBINT04011E_REV_A/default.htm"))
        insDoc(Level3_Desc, gLnk("B", "KAREL and TPP Program Diagnostic Option ", "../MARAIBKTP05011E_REV_A/toc.htm"))
        insDoc(Level3_Desc, gLnk("B", "OLRP TPP Translator", "../MARO3TP5210901E_REV_B/toc.htm"))
        insDoc(Level3_Desc, gLnk("B", "OLRP TPP Translator  ", "../MAROIBTPP05011E_REV_A/toc.htm"))
        insDoc(Level3_Desc, gLnk("B", "SPI Interface Setup and Operations", "../MARO2SPIS11801E_REV_B/book.pdf"))
      Level3_Desc = insFld(Level2_Desc, gFld("Reference"))
        insDoc(Level3_Desc, gLnk("B", "Compatibility Overview: R-J3 to R-J3iB Controller", "MARO62COM10011E_REV_A/default.htm"))
        insDoc(Level3_Desc, gLnk("B", "Error Code", "../MAROIBECD05011E_REV_A/toc.htm"))
        insDoc(Level3_Desc, gLnk("B", "Internet Options Setup and Operations", "MAROIBINT04011E_REV_A/default.htm"))
        insDoc(Level3_Desc, gLnk("B", "KAREL Reference", "MCRA3SSKR05001E_REV_A/toc.htm"))
    Level2_Desc = insFld(Level1_Desc, gFld("V5.30"))
      Level3_Desc = insFld(Level2_Desc, gFld("Communications and Network I/O"))
        insDoc(Level3_Desc, gLnk("B", "Cimplicity HMI Operator  ", "../MAROIBHMI09011E_REV_A/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "ControlNet Interface User Guide", "../MARO3CLNT11001E_REV_A/toc.htm"))
        insDoc(Level3_Desc, gLnk("B", "DeviceNet Setup and Operations", "../MARO3DENT05001E_REV_B/toc.htm"))
        insDoc(Level3_Desc, gLnk("B", "Genius Network Interface for GE Fanuc User Guide ", "../MARUIBGNI05011E_REV_A/toc.htm"))
        insDoc(Level3_Desc, gLnk("B", "Internet Options Setup and Operation", "../MARO3IO5311001E_REV_A/toc.htm"))
        insDoc(Level3_Desc, gLnk("B", "Remote I/O Interface for an Allen-Bradley PLC User guide", "../MARU3ABIO10901E_REV_B/toc.htm"))
      Level3_Desc = insFld(Level2_Desc, gFld("Operations"))
        insDoc(Level3_Desc, gLnk("B", "ArcTool Setup and Operations", "../MARO3ARTL11001E_REV_C/toc.htm"))
        insDoc(Level3_Desc, gLnk("B", "DispenseTool Plug-in to SpotTool+ Setup and Operations", "../MARO3DIST11001E_REV_A/toc.htm"))
        insDoc(Level3_Desc, gLnk("B", "DispenseTool Setup and Operations", "../MARO3DSTL11001E_REV_A/toc.htm"))
        insDoc(Level3_Desc, gLnk("B", "HandlingTool Setup and Operations", "../MARO3HD5310001E_REV_B/toc.htm"))
        insDoc(Level3_Desc, gLnk("B", "PaintTool Setup and Operations", "../MARO3PNTL11001E_REV_D/toc.htm"))
        insDoc(Level3_Desc, gLnk("B", "PalletTool Setup and Operations", "../MARO3PT5311001E_REV_A/toc.htm"))
        insDoc(Level3_Desc, gLnk("B", "RemovalTool Setup and Operations", "../MARO3RT5210901E_REV_B/toc.htm"))
        insDoc(Level3_Desc, gLnk("B", "Software Installation", "../MARF3SFTI11001E_REV_B/toc.htm"))
        insDoc(Level3_Desc, gLnk("B", "SpotTool+ Setup and Operations", "../MARO3SPTO11001E_REV_B/toc.htm"))
      Level3_Desc = insFld(Level2_Desc, gFld("Options"))
        insDoc(Level3_Desc, gLnk("B", "Accustat Maintenance", "../MARA3ACCU11001E_REV_A/toc.htm"))
        insDoc(Level3_Desc, gLnk("B", "AssistTool Setup and Operations", "../MARO3ASTL01011E_REV_A/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Continuous Turn User Guide", "../MARU3CT5111801E_REV_B/toc.htm"))
        insDoc(Level3_Desc, gLnk("B", "Coordinated Motion Setup and Operations  ", "../MAROIBCM605011E_REV_A/toc.htm"))
        insDoc(Level3_Desc, gLnk("B", "I-21i Force Sensor Operator", "../MARA3I2L107901E_REV_B/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Integrated Welding Control Interface User Guide", "../MARO3IS5101901E_REV_B/toc.htm"))
        insDoc(Level3_Desc, gLnk("B", "Linetracking Setup and Operations", "../MARO3LNTK11001E_REV_A/toc.htm"))
        insDoc(Level3_Desc, gLnk("B", "OLRP TPP Translator", "../MARO3TP5210901E_REV_B/toc.htm"))
      Level3_Desc = insFld(Level2_Desc, gFld("Reference"))
        insDoc(Level3_Desc, gLnk("B", "Compatibility Overview: R-J3 to R-J3iB Controller ", "MARO62COM10011E_REV_A/default.htm"))
        insDoc(Level3_Desc, gLnk("B", "Error Code", "../MARA3ERCD11001E_REV_B/toc.htm"))
        insDoc(Level3_Desc, gLnk("B", "KAREL Reference", "MCXX3KR5311001E_REV_A/toc.htm"))
        insDoc(Level3_Desc, gLnk("B", "KAREL and TPP Program Diagnostic Option", "../MARA3KLTP05001E_REV_B/toc.htm"))
        insDoc(Level3_Desc, gLnk("B", "Software Reference", "MCXX3SR5311001E_REV_A/toc.htm"))
    Level2_Desc = insFld(Level1_Desc, gFld("V6.10"))
      Level3_Desc = insFld(Level2_Desc, gFld("Communications and Network I/O"))
        insDoc(Level3_Desc, gLnk("B", "DeviceNet Interface Operators Manual", "B-81714EN_REV_1/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Ethernet Function Operator", "../MAROIMEFN04021E_REV_A/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "HMI User Guide", "../MARUIBHMI05011E_REV_A/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "PROFIBUS-DP (12M) Interface Function Operator  ", "../MARAIBPRO05011E_REV_A/toc.htm"))
        insDoc(Level3_Desc, gLnk("B", "Remote I/O Interface for an Allen-Bradley PLC User Guide ", "../MARUIBABI05011E_REV_A/toc.htm"))
      Level3_Desc = insFld(Level2_Desc, gFld("Operations"))
        insDoc(Level3_Desc, gLnk("B", "LR HandlingTool Operator", "../MAROIBLRH02021E_REV_A/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Software Installation  ", "MARFIB6201001E_REV_A/default.htm"))
      Level3_Desc = insFld(Level2_Desc, gFld("Options"))
        insDoc(Level3_Desc, gLnk("B", "Continuous Turn User Guide", "../MARU62CNT10011E_REV_A/toc.htm"))
        insDoc(Level3_Desc, gLnk("B", "I-21i Vision Sensor", "../MAROI21VS04021E_REV_A/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "KAREL and TPP Program Diagnostic Option ", "../MARAIBKTP05011E_REV_A/toc.htm"))
        insDoc(Level3_Desc, gLnk("B", "Linetracking Setup and Operations ", "../MARO62LNT10011E_REV_B/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "OLRP TPP Translator  ", "../MAROIBTPP05011E_REV_A/toc.htm"))
        insDoc(Level3_Desc, gLnk("B", "SPI Interface Setup and Operations", "../MARO2SPIS11801E_REV_B/book.pdf"))
      Level3_Desc = insFld(Level2_Desc, gFld("Reference"))
        insDoc(Level3_Desc, gLnk("B", "Error Code", "MARO62ECD10011E_REV_A/default.htm"))
        insDoc(Level3_Desc, gLnk("B", "KAREL Reference  ", "MCXXIBK6209011E_REV_A/default.htm"))
        insDoc(Level3_Desc, gLnk("B", "Software Reference  ", "MCXXISR6210011E_REV_B/default.htm"))
    Level2_Desc = insFld(Level1_Desc, gFld("V6.11"))
      Level3_Desc = insFld(Level2_Desc, gFld("Communications and Network I/O"))
        insDoc(Level3_Desc, gLnk("B", "Cimplicity HMI Operator  ", "../MAROIBHMI09011E_REV_A/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "ControlNet Interface User Guide", "../MAROIBCNT05011E_REV_A/toc.htm"))
        insDoc(Level3_Desc, gLnk("B", "DeviceNet Setup and Operations", "MARO62DVN09011E_REV_A/default.htm"))
        insDoc(Level3_Desc, gLnk("B", "Genius Network Interface for GE Fanuc User Guide ", "../MARUIBGNI05011E_REV_A/toc.htm"))
        insDoc(Level3_Desc, gLnk("B", "HMI User Guide", "../MARUIBHMI05011E_REV_A/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Internet Options Setup and Operations", "MAROIBINT04011E_REV_A/default.htm"))
        insDoc(Level3_Desc, gLnk("B", "PROFIBUS-DP (12M) Interface Function Operator  ", "../MARAIBPRO05011E_REV_A/toc.htm"))
        insDoc(Level3_Desc, gLnk("B", "Remote I/O Interface for an Allen-Bradley PLC User Guide ", "../MARUIBABI05011E_REV_A/toc.htm"))
      Level3_Desc = insFld(Level2_Desc, gFld("Operations"))
        insDoc(Level3_Desc, gLnk("B", "HandlingTool Setup and Operations", "../MAROIBHND04011E_REV_A/toc.htm"))
        insDoc(Level3_Desc, gLnk("B", "RemovalTool Setup and Operations", "MARO62RMT09011E_REV_B/default.htm"))
        insDoc(Level3_Desc, gLnk("B", "Software Installation", "../MARFIBGEN05011E_REV_A/toc.htm"))
        insDoc(Level3_Desc, gLnk("B", "SpotTool+ Setup and Operations", "../MAROIBSPT04011E_REV_A/toc.htm"))
      Level3_Desc = insFld(Level2_Desc, gFld("Options"))
        insDoc(Level3_Desc, gLnk("B", "Continuous Turn User Guide", "../MARU62CNT10011E_REV_A/toc.htm"))
        insDoc(Level3_Desc, gLnk("B", "Coordinated Motion Setup and Operations  ", "../MAROIBCM605011E_REV_A/toc.htm"))
        insDoc(Level3_Desc, gLnk("B", "FAPT Ladder-III Operator ", "../MAROFAPT05011E_REV_B/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Integrated PMC Operator", "../MARX3PMC011001E_REV_B/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Integrated Welding Control Interface User Guide", "../MAROIBIWC05011E_REV_A/toc.htm"))
        insDoc(Level3_Desc, gLnk("B", "KAREL and TPP Program Diagnostic Option ", "../MARAIBKTP05011E_REV_A/toc.htm"))
        insDoc(Level3_Desc, gLnk("B", "Linetracking Setup and Operations ", "../MARO62LNT10011E_REV_B/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "OLRP TPP Translator  ", "../MAROIBTPP05011E_REV_A/toc.htm"))
        insDoc(Level3_Desc, gLnk("B", "SPI Interface Setup and Operations", "../MARO2SPIS11801E_REV_B/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Servo Gun Function Operator", "../MARO62SGF09011E_REV_A/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Servo Gun Function Supplementary", "../MAROIBSVG05011E_REV_E/book.pdf"))
      Level3_Desc = insFld(Level2_Desc, gFld("Reference"))
        insDoc(Level3_Desc, gLnk("B", "Compatibility Overview: R-J3 to R-J3iB Controller ", "MARO62COM10011E_REV_A/default.htm"))
        insDoc(Level3_Desc, gLnk("B", "Error Code", "MAROI62ER08021E_REV_A/book01.html"))
        insDoc(Level3_Desc, gLnk("B", "KAREL Reference", "MCXXIBKR6105011E_REV_A/default.htm"))
        insDoc(Level3_Desc, gLnk("B", "Software Reference", "MCXXIBSR6105011E_REV_A/default.htm"))
    Level2_Desc = insFld(Level1_Desc, gFld("V6.20"))
      Level3_Desc = insFld(Level2_Desc, gFld("Communications and Network I/O"))
        insDoc(Level3_Desc, gLnk("B", "Cimplicity HMI Operator  ", "../MAROIBHMI09011E_REV_A/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "ControlNet Interface User Guide", "../MAROIBCNT05011E_REV_A/toc.htm"))
        insDoc(Level3_Desc, gLnk("B", "DeviceNet Setup and Operations", "MARO62DVN09011E_REV_A/default.htm"))
        insDoc(Level3_Desc, gLnk("B", "Genius Network Interface for GE Fanuc User Guide ", "../MARUIBGNI05011E_REV_A/toc.htm"))
        insDoc(Level3_Desc, gLnk("B", "HMI User Guide", "../MARUIBHMI05011E_REV_A/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Internet Options Setup and Operations ", "MARO62INT09011E_REV_A/default.htm"))
        insDoc(Level3_Desc, gLnk("B", "PROFIBUS-DP (12M) Interface Function Operator  ", "../MARAIBPRO05011E_REV_A/toc.htm"))
        insDoc(Level3_Desc, gLnk("B", "Remote I/O Interface for an Allen-Bradley PLC User Guide ", "../MARUIBABI05011E_REV_A/toc.htm"))
      Level3_Desc = insFld(Level2_Desc, gFld("Operations"))
        insDoc(Level3_Desc, gLnk("B", "ArcTool Setup and Operations  ", "../MAROIBARC10011E_REV_A/toc.htm"))
        insDoc(Level3_Desc, gLnk("B", "DispenseTool Plug-in to SpotTool+ Setup and Operations ", "../MARO62DTS10011E_REV_A/toc.htm"))
        insDoc(Level3_Desc, gLnk("B", "DispenseTool Setup and Operations ", "../MAROIBDTL05011E_REV_A/toc.htm"))
        insDoc(Level3_Desc, gLnk("B", "HandlingTool Setup and Operations", "MARO62HND09011E_REV_B/default.htm"))
        insDoc(Level3_Desc, gLnk("B", "PalletTool Setup and Operations  ", "../MARO62PLT09011E_REV_A/toc.htm"))
        insDoc(Level3_Desc, gLnk("B", "RemovalTool Setup and Operations", "MARO62RMT09011E_REV_B/default.htm"))
        insDoc(Level3_Desc, gLnk("B", "Software Installation  ", "MARFIB6201001E_REV_A/default.htm"))
        insDoc(Level3_Desc, gLnk("B", "SpotTool+ Setup and Operations  ", "../MARO62SPT10011E_REV_B/toc.htm"))
      Level3_Desc = insFld(Level2_Desc, gFld("Options"))
        insDoc(Level3_Desc, gLnk("B", "Continuous Turn User Guide", "../MARU62CNT10011E_REV_A/toc.htm"))
        insDoc(Level3_Desc, gLnk("B", "Coordinated Motion Setup and Operations  ", "../MAROIBCM605011E_REV_A/toc.htm"))
        insDoc(Level3_Desc, gLnk("B", "Dengensha Integrated Welding Control Operator", "../MAROIIWCD05021E_REV_A/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "FAPT Ladder-III Operator ", "../MAROFAPT05011E_REV_B/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "I-21i Vision Sensor", "../MAROI21VS04021E_REV_A/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Integrated PMC Operator", "../MARX3PMC011001E_REV_B/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Integrated Welding Control Interface User Guide", "../MAROIBIWC05011E_REV_A/toc.htm"))
        insDoc(Level3_Desc, gLnk("B", "KAREL and TPP Program Diagnostic Option ", "../MARAIBKTP05011E_REV_A/toc.htm"))
        insDoc(Level3_Desc, gLnk("B", "Linetracking Setup and Operations ", "../MARO62LNT10011E_REV_B/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "OLRP TPP Translator  ", "../MAROIBTPP05011E_REV_A/toc.htm"))
        insDoc(Level3_Desc, gLnk("B", "SPI Interface Setup and Operations", "../MARO2SPIS11801E_REV_B/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Servo Gun Function Operator", "../MAROIBSGF05011E_REV_E/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Servo Gun Function Supplementary", "../MAROIBSVG05011E_REV_E/book.pdf"))
      Level3_Desc = insFld(Level2_Desc, gFld("Reference"))
        insDoc(Level3_Desc, gLnk("B", "Compatibility Overview: R-J3 to R-J3iB Controller ", "MARO62COM10011E_REV_A/default.htm"))
        insDoc(Level3_Desc, gLnk("B", "Error Code", "MARO62ECD10011E_REV_A/default.htm"))
        insDoc(Level3_Desc, gLnk("B", "KAREL Reference  ", "MARAIKARR08021E_REV_A/book01.html"))
        insDoc(Level3_Desc, gLnk("B", "Software Reference  ", "MCXXISR6210011E_REV_B/default.htm"))
    Level2_Desc = insFld(Level1_Desc, gFld("V6.21"))
      Level3_Desc = insFld(Level2_Desc, gFld("Operations"))
        insDoc(Level3_Desc, gLnk("B", "PalletTool Setup and Operations", "MAROIBPAL05021E_REV_A/default.htm"))
        insDoc(Level3_Desc, gLnk("B", "SpotTool+ with Dispensetool Plug-in Setup and Operations", "MAROIBDTS05021E_REV_A/default.htm"))
      Level3_Desc = insFld(Level2_Desc, gFld("Options"))
        insDoc(Level3_Desc, gLnk("B", "Coordinated Motion Setup and Operations  ", "MAROICM6206021E_REV_B/book01.html"))
        insDoc(Level3_Desc, gLnk("B", "Servo Gun Function Operator", "../MAROIBSGF05011E_REV_E/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Servo Gun Function Supplementary", "../MAROIBSVG05011E_REV_E/book.pdf"))
      Level3_Desc = insFld(Level2_Desc, gFld("Reference"))
        insDoc(Level3_Desc, gLnk("B", "Error Code", "MAROI62ER08021E_REV_A/book01.html"))
        insDoc(Level3_Desc, gLnk("B", "KAREL Reference  ", "MARAIKARR08021E_REV_A/book01.html"))
        insDoc(Level3_Desc, gLnk("B", "Software Reference", "MARAIBSRR05021E_REV_B/book01.html"))
    Level2_Desc = insFld(Level1_Desc, gFld("V6.22"))
      Level3_Desc = insFld(Level2_Desc, gFld("Communications and Network I/O"))
        insDoc(Level3_Desc, gLnk("B", "Cimplicity HMI Operator  ", "MAROIBHMI09011E_REV_A/"))
        insDoc(Level3_Desc, gLnk("B", "ControlNet Interface User Guide", "MAROIBCNT05011E_REV_A/"))
        insDoc(Level3_Desc, gLnk("B", "DeviceNet Setup and Operations", "MAROIBDNT20501E_REV_A/book01.html"))
        insDoc(Level3_Desc, gLnk("B", "Ethernet Global Data Setup and Operations ", "MARO62EGD09011E_REV_A/book01.html"))
        insDoc(Level3_Desc, gLnk("B", "Genius Network Interface for GE Fanuc User Guide ", "MARUIBGNI05011E_REV_A/"))
        insDoc(Level3_Desc, gLnk("B", "HMI User Guide", "MARUIBHMI05011E_REV_A/"))
        insDoc(Level3_Desc, gLnk("B", "Internet Options Setup and Operations ", "MAROIBIO205021E_REV_A/book01.html"))
        insDoc(Level3_Desc, gLnk("B", "PROFIBUS-DP (12M) Interface Function Operator  ", "MARAIBPRO05011E_REV_A/"))
        insDoc(Level3_Desc, gLnk("B", "Remote I/O Interface for an Allen-Bradley PLC User Guide ", "MARUIBABI05011E_REV_A/"))
      Level3_Desc = insFld(Level2_Desc, gFld("Operations"))
        insDoc(Level3_Desc, gLnk("B", "ArcTool Setup and Operations", "MAROIA62208021E_REV_A/book01.html"))
        insDoc(Level3_Desc, gLnk("B", "DispenseTool Setup and Operations", "MAROIBDTL05021E_REV_A/book01.html"))
        insDoc(Level3_Desc, gLnk("B", "HandlingTool Setup and Operations", "MAROIH62208021E_REV_A/book01.html"))
        insDoc(Level3_Desc, gLnk("B", "PaintTool Setup and Operations", "MAROIBPNT05021E_REV_A/"))
        insDoc(Level3_Desc, gLnk("B", "RemovalTool Setup and Operations", "MAROIRMVL08021E_REV_A/book01.html"))
        insDoc(Level3_Desc, gLnk("B", "Software Installation", "../MARFIB62208021E_REV_A/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "SpotTool+ Setup and Operations", "MAROIBSPT05021E_REV_A/"))
      Level3_Desc = insFld(Level2_Desc, gFld("Options"))
        insDoc(Level3_Desc, gLnk("B", "Continuous Turn User Guide", "MARU62CNT10011E_REV_A/"))
        insDoc(Level3_Desc, gLnk("B", "Coordinated Motion Setup and Operations  ", "MAROICM6206021E_REV_B/book01.html"))
        insDoc(Level3_Desc, gLnk("B", "Dengensha Integrated Welding Control Operator", "MAROIIWCD05021E_REV_A/"))
        insDoc(Level3_Desc, gLnk("B", "FAPT Ladder-III Operator ", "MAROFAPT05011E _REV_B/"))
        insDoc(Level3_Desc, gLnk("B", "Integrated PMC Operator", "MARX3PMC011001E_REV_B/"))
        insDoc(Level3_Desc, gLnk("B", "Integrated Welding Control Interface User Guide", "MAROIBIWC05011E_REV_A/"))
        insDoc(Level3_Desc, gLnk("B", "KAREL and TPP Program Diagnostic Option ", "MARAIBKTP05011E_REV_A/"))
        insDoc(Level3_Desc, gLnk("B", "Linetracking Setup and Operations ", "../MAROILINE08021E_REV_A/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "OLRP TPP Translator  ", "MAROIBTPP05011E_REV_A/"))
        insDoc(Level3_Desc, gLnk("B", "RemovalTool Setup and Operations", "MARO62RMT09011E_REV_B/"))
        insDoc(Level3_Desc, gLnk("B", "SPI Interface Setup and Operations", "MARO2SPIS11801E_REV_B/"))
        insDoc(Level3_Desc, gLnk("B", "Servo Gun Function Operator", "../MAROIBSGF05011E_REV_E/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Servo Gun Function Supplementary", "../MAROIBSVG05011E_REV_E/book.pdf"))
      Level3_Desc = insFld(Level2_Desc, gFld("Reference"))
        insDoc(Level3_Desc, gLnk("B", "Compatibility Overview: R-J3 to R-J3iB Controller ", "MARO62COM10011E_REV_A/"))
        insDoc(Level3_Desc, gLnk("B", "Error Code", "MAROI62ER08021E_REV_A/book01.html"))
        insDoc(Level3_Desc, gLnk("B", "KAREL Reference  ", "MARAIKARR08021E_REV_A/book01.html"))
        insDoc(Level3_Desc, gLnk("B", "Software Reference", "MARAIBSRR05021E_REV_B/book01.html"))
insDoc(foldersTree, gLnk("B", "<Font size=1>   FANUC America Corporation 1999-2013. All rights reserved. </Font>", "../../policies/terms.htm"))
