// You can find instructions for this file here: http://www.treeview.net
USETEXTLINKS = 1  //replace 0 with 1 for hyperlinks
STARTALLOPEN = 0 //replace 0 with 1 to show the whole tree
ICONPATH = 'menu_files/' //change if the gif's folder is a subfolder, for example: 'images/'

foldersTree = gFld("<font size=3><b>MURAUIBPL07171E Rev I</b></font>")
  Level1_Desc = insFld(foldersTree, gFld("Electrical Manuals"))
    Level2_Desc = insFld(Level1_Desc, gFld("_Safety"))
      Level3_Desc = insFld(Level2_Desc, gFld("Safety Handbook"))
        insDoc(Level3_Desc, gLnk("B", "Safety Handbook", "B-80687EN_REV_17/book.pdf"))
    Level2_Desc = insFld(Level1_Desc, gFld("R-30iB Compact Plus"))
      Level3_Desc = insFld(Level2_Desc, gFld("R-30iB Compact Plus Controller"))
        insDoc(Level3_Desc, gLnk("B", "Controller Maintenance", "B-84035EN_REV_04/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "HSI Pulse Module", "MARO3HSIP12901E_REV_F/book.pdf"))
    Level2_Desc = insFld(Level1_Desc, gFld("R-30iB Mate Plus"))
      Level3_Desc = insFld(Level2_Desc, gFld("R-30iB Mate Plus Controller"))
        insDoc(Level3_Desc, gLnk("B", "Controller Maintenance", "B-83525EN_REV_09/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "HSI Pulse Module", "MARO3HSIP12901E_REV_F/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Local Stop Function with STO Maintenance", "MAREBLSTO02131E_REV_A/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Open Air Controller Maintenance", "B-83555EN_REV_08/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "P-40iA Controller Addendum", "MARXTP40A02181E_REV_A/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "SPC-20 Paint Controller Addendum", "MAREYCMTE08201E_REV_A/book.pdf"))
      Level3_Desc = insFld(Level2_Desc, gFld("Sensor Mechanical Unit/Control Unit"))
        insDoc(Level3_Desc, gLnk("B", "Sensor Mechanical Unit/Control Unit Operator", "B-83984EN_REV_03/book.pdf"))
    Level2_Desc = insFld(Level1_Desc, gFld("R-30iB Mini Plus"))
      Level3_Desc = insFld(Level2_Desc, gFld("R-30iB Mini Plus Controller"))
        insDoc(Level3_Desc, gLnk("B", "Controller Maintenance", "B-84175EN_REV_02/book.pdf"))
    Level2_Desc = insFld(Level1_Desc, gFld("R-30iB Plus"))
      Level3_Desc = insFld(Level2_Desc, gFld("R-30iB Plus Controller"))
        insDoc(Level3_Desc, gLnk("B", "Auxiliary Axis Option Maintenance", "MAREBAUXA07131E_REV_A/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Controller Maintenance", "B-83195EN_REV_11/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "HSI Pulse Module", "MARO3HSIP12901E_REV_F/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Local Stop Function with STO Maintenance", "MAREBLSTO02131E_REV_A/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "P-1000iA/P35iA Automotive Paint Controller Addendum", "MARXU10AU10191E_REV_B/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "P-250iB Automotive Paint Controller Addendum", "MARXUP25A07191E_REV_A/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "P-250iB General Industry Paint Controller Addendum", "MARXUP25G10191E_REV_A/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "P-350iA General Industry Paint Controller Addendum", "MARXUP35010201E_REV_A/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "P-700iB/P-20iB/P-25iB Automotive Paint Controller Addendum", "MARXUP7AU10191E_REV_A/book.pdf"))
      Level3_Desc = insFld(Level2_Desc, gFld("Sensor Mechanical Unit/Control Unit"))
        insDoc(Level3_Desc, gLnk("B", "Sensor Mechanical Unit/Control Unit Operator", "B-83984EN_REV_03/book.pdf"))
  Level1_Desc = insFld(foldersTree, gFld("Mechanical Manuals"))
    Level2_Desc = insFld(Level1_Desc, gFld("_Safety"))
      Level3_Desc = insFld(Level2_Desc, gFld("Safety Handbook"))
        insDoc(Level3_Desc, gLnk("B", "Safety Handbook", "B-80687EN_REV_17/book.pdf"))
    Level2_Desc = insFld(Level1_Desc, gFld("R-30iB Compact Plus/SCARA"))
      Level3_Desc = insFld(Level2_Desc, gFld("SR-12iA"))
        insDoc(Level3_Desc, gLnk("B", "SR-12iA, SR-20iA Mechanical Unit Operator", "B-84164EN_REV_02/book.pdf"))
      Level3_Desc = insFld(Level2_Desc, gFld("SR-20iA"))
        insDoc(Level3_Desc, gLnk("B", "SR-12iA, SR-20iA Mechanical Unit Operator", "B-84164EN_REV_02/book.pdf"))
      Level3_Desc = insFld(Level2_Desc, gFld("SR-3iA"))
        insDoc(Level3_Desc, gLnk("B", "SR-3iA Mechanical Unit Operator", "B-84024EN_REV_05/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "SR-3iA/SR-6iA Startup Guide (Software Version 9.10P/07)", "MARGUSR3601181E_REV_B/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "SR-3iA/SR-6iA Startup Guide (Software Version 9.10P/09)", "MARGXSR3605181E_REV_A/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "SR-3iA/SR-6iA/SR-12iA Startup Guide (Software Version 9.10P/10 and later)", "MARGXSR3606181E_REV_E/book.pdf"))
      Level3_Desc = insFld(Level2_Desc, gFld("SR-6iA"))
        insDoc(Level3_Desc, gLnk("B", "SR-3iA Mechanical Unit Operator", "B-84024EN_REV_05/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "SR-3iA/SR-6iA Startup Guide (Software Version 9.10P/07)", "MARGUSR3601181E_REV_B/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "SR-3iA/SR-6iA Startup Guide (Software Version 9.10P/09)", "MARGXSR3605181E_REV_A/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "SR-3iA/SR-6iA/SR-12iA Startup Guide (Software Version 9.10P/10 and later)", "MARGXSR3606181E_REV_E/book.pdf"))
      Level3_Desc = insFld(Level2_Desc, gFld("Startup Guide"))
        insDoc(Level3_Desc, gLnk("B", "SR-3iA/SR-6iA Startup Guide (Software Version 9.10P/07)", "MARGUSR3601181E_REV_B/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "SR-3iA/SR-6iA Startup Guide (Software Version 9.10P/09)", "MARGXSR3605181E_REV_A/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "SR-3iA/SR-6iA/SR-12iA Startup Guide (Software Version 9.10P/10 and later)", "MARGXSR3606181E_REV_E/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "ZDT Startup Guide Set (IR809 Data Collector)", "SERGGI80902181E_REV_A/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "ZDT Startup Guide Set (VM Data Collector)", "SERGGIVMA03181E_REV_D/book.pdf"))
    Level2_Desc = insFld(Level1_Desc, gFld("R-30iB Mate Plus"))
      Level3_Desc = insFld(Level2_Desc, gFld("ARC Mate 100iC/12, M-10iA/12, /7L, /12S, /8L"))
        insDoc(Level3_Desc, gLnk("B", "/12, /7L, /12S, /8L Mechanical Unit Operator", "B-83654EN_REV_06/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "ARC Mate 100iC/M-10iA, 100iD/M-10iD Startup Guide", "MARGUM10A04171E_REV_D/book.pdf"))
      Level3_Desc = insFld(Level2_Desc, gFld("ARC Mate 100iC/M-10iA"))
        insDoc(Level3_Desc, gLnk("B", "/e, /6L, /10S, /10M, /10MS Mechanical Unit Operator", "MAROCAM1010071E_REV_P/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "ARC Mate 100iC/M-10iA, 100iD/M-10iD Startup Guide", "MARGUM10A04171E_REV_D/book.pdf"))
      Level3_Desc = insFld(Level2_Desc, gFld("ARC Mate 100iD/M-10iD"))
        insDoc(Level3_Desc, gLnk("B", "ARC Mate 100iC/M-10iA, 100iD/M-10iD Startup Guide", "MARGUM10A04171E_REV_D/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Mechanical Unit Operator", "B-83944EN_REV_04/book.pdf"))
      Level3_Desc = insFld(Level2_Desc, gFld("ARC Mate 120iD/M-20iD"))
        insDoc(Level3_Desc, gLnk("B", "/10L, /20M, /12L, /35M Mechanical Unit Operator", "B-82874EN_REV_13/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "ARC Mate 100iC/M-10iA, 100iD/M-10iD Startup Guide", "MARGUM10A04171E_REV_D/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Mechanical Unit Operator", "B-84074EN_REV_04/book.pdf"))
      Level3_Desc = insFld(Level2_Desc, gFld("ARC Mate 50iD, /7H/7C/7WP/7L/7LC"))
        insDoc(Level3_Desc, gLnk("B", "Arc Mate 50iD Series Startup Guide", "MARGTAM5011161E_REV_C/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Mechanical Unit Operator", "MAROT200D01121E_REV_G/book.pdf"))
      Level3_Desc = insFld(Level2_Desc, gFld("Arc Welding Power Supply"))
        insDoc(Level3_Desc, gLnk("B", "Daihen Digital Operators", "MAROBDWLD10151E_REV_A/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "FRONIUS TPS/i Welding Power Supply", "MAROWFTPS12181E_REV_A/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Miller Weld Equipment Library Option", "MAROBMWLD02131E_REV_D/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "SKS Weld Equipment Library Option", "MAROBSKSW02151E_REV_C/book.pdf"))
      Level3_Desc = insFld(Level2_Desc, gFld("CR-4iA, CR-7iA, CR-7iA/L, CR-14iA/L"))
        insDoc(Level3_Desc, gLnk("B", "CR-4iA, CR-7iA, CR-7iA/L, CR-14iA/L Startup Guide", "MARGUCR7A02171E_REV_F/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Mechanical Unit Operator", "B-83774EN_REV_04/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Small Hand Guidance Operator", "MAROBSHGD02191E_REV_A/book.pdf"))
      Level3_Desc = insFld(Level2_Desc, gFld("DR-3iB"))
        insDoc(Level3_Desc, gLnk("B", "DR-3iB Startup Guide", "MARGUDR3I04211E_REV_A/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Mechanical Unit Operator", "B-84114EN_REV_01/book.pdf"))
      Level3_Desc = insFld(Level2_Desc, gFld("LR Mate 200iD, /7H/7C/7WP/7L/7LC"))
        insDoc(Level3_Desc, gLnk("B", "LR Mate 200iD Series, ER-4iA Startup Guide", "MARGT200D11161E_REV_F/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Mechanical Unit Operator", "MAROT200D01121E_REV_G/book.pdf"))
      Level3_Desc = insFld(Level2_Desc, gFld("LR Mate 200iD/4S/4SH/4SC, ER-4iA"))
        insDoc(Level3_Desc, gLnk("B", "LR Mate 200iD Series, ER-4iA Startup Guide", "MARGT200D11161E_REV_F/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Mechanical Unit Operator", "MAROTID4S06131E_REV_E/book.pdf"))
      Level3_Desc = insFld(Level2_Desc, gFld("M-1iA"))
        insDoc(Level3_Desc, gLnk("B", "/0.5S, /0.5A, /1H, /0.5SL, /0.5AL, /1HL Mechanical Unit Operator", "B-83084EN_REV_10/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "M-1iA Series Startup Guide", "MARGTM1IA06171E_REV_B/book.pdf"))
      Level3_Desc = insFld(Level2_Desc, gFld("M-20iB"))
        insDoc(Level3_Desc, gLnk("B", "/25/35S/25C Mechanical Unit Operator", "MAROBM22503161E_REV_C/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "M-20iB Startup Guide", "MARGUM2IB04171E_REV_C/book.pdf"))
      Level3_Desc = insFld(Level2_Desc, gFld("M-2iA"))
        insDoc(Level3_Desc, gLnk("B", "/3S, /3SL, /6H, /6HL, /3A, /3AL Mechanical Unit Operator", "MAROBM2IA01131E_REV_E/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "M-2iA/M-3iA Series Startup Guide", "MARGUM2M306171E_REV_B/book.pdf"))
      Level3_Desc = insFld(Level2_Desc, gFld("M-710iC"))
        insDoc(Level3_Desc, gLnk("B", "/50, /70, /50H, /50S, /45M, /50E Mechanical Unit Operator", "MARAC710C02061E_REV_L/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "General Robot Startup Guide", "MARGGGPSG08171E_REV_B/book.pdf"))
      Level3_Desc = insFld(Level2_Desc, gFld("M-710iC/20L, /12L, /20M"))
        insDoc(Level3_Desc, gLnk("B", "General Robot Startup Guide", "MARGGGPSG08171E_REV_B/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "M-710iC/20L, /12L, 20M Mechanical Unit Operator", "MAROCM71009061E_REV_I/book.pdf"))
      Level3_Desc = insFld(Level2_Desc, gFld("P-40iA"))
        insDoc(Level3_Desc, gLnk("B", "Mechanical Unit Operator", "MAROP40IA07171E_REV_B/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "P-40iA R-30iB Mate Plus Startup Guide", "MARGTP40A05081E_REV_B/book.pdf"))
      Level3_Desc = insFld(Level2_Desc, gFld("P-50iB"))
        insDoc(Level3_Desc, gLnk("B", "Mechanical Unit Operator", "MAROT50IB12141E_REV_C/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "R-30iB Mate Plus P-50iB Startup Guide", "MARGUP50I07201E_REV_A/book.pdf"))
      Level3_Desc = insFld(Level2_Desc, gFld("Paint Mate 200iA"))
        insDoc(Level3_Desc, gLnk("B", "Mechanical Unit Operator", "MAROCPM2001091E_REV_C/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Paint Mate 200iA Startup Guide", "MARGPPM2008181E_REV_B/book.pdf"))
      Level3_Desc = insFld(Level2_Desc, gFld("Purged Enclosures"))
        insDoc(Level3_Desc, gLnk("B", "Purged Enclosure/Purged Motor Box Operator", "MAROBPPEB03201E_REV_A/book.pdf"))
      Level3_Desc = insFld(Level2_Desc, gFld("R-1000iA"))
        insDoc(Level3_Desc, gLnk("B", "General Robot Startup Guide", "MARGGGPSG08171E_REV_B/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Mechanical Unit Operator", "B-83004EN_REV_09/book.pdf"))
      Level3_Desc = insFld(Level2_Desc, gFld("R-2000iC"))
        insDoc(Level3_Desc, gLnk("B", "Mechanical Unit Operator", "B-83644EN_REV_07/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "R-2000iC/R-2000iD Startup Guide", "MARGUR2IC10161E_REV_C/book.pdf"))
      Level3_Desc = insFld(Level2_Desc, gFld("Sensor Mechanical Unit/Control Unit"))
        insDoc(Level3_Desc, gLnk("B", "Sensor Mechanical Unit/Control Unit Operator", "B-83984EN_REV_03/book.pdf"))
      Level3_Desc = insFld(Level2_Desc, gFld("Servo Positioner"))
        insDoc(Level3_Desc, gLnk("B", "1-Axis Servo Positioner Mechanical Operator", "B-84154EN_REV_01/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "2-axis Servo Positioner Operator", "B-82534EN_REV_01/book.pdf"))
      Level3_Desc = insFld(Level2_Desc, gFld("Startup Guide"))
        insDoc(Level3_Desc, gLnk("B", "ARC Mate 100iC/M-10iA, 100iD/M-10iD Startup Guide", "MARGUM10A04171E_REV_D/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Arc Mate 50iD Series Startup Guide", "MARGTAM5011161E_REV_C/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "CR-4iA, CR-7iA, CR-7iA/L, CR-14iA/L Startup Guide", "MARGUCR7A02171E_REV_F/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "DR-3iB Startup Guide", "MARGUDR3I04211E_REV_A/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "LR Mate 200iD Series, ER-4iA Startup Guide", "MARGT200D11161E_REV_F/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "M-1iA Series Startup Guide", "MARGTM1IA06171E_REV_B/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "M-20iB Startup Guide", "MARGUM2IB04171E_REV_C/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "M-2iA/M-3iA Series Startup Guide", "MARGUM2M306171E_REV_B/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "P-40iA R-30iB Mate Plus Startup Guide", "MARGTP40A05081E_REV_B/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Paint Mate 200iA Startup Guide", "MARGPPM2008181E_REV_B/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "R-2000iC/R-2000iD Startup Guide", "MARGUR2IC10161E_REV_C/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "R-30iB Mate Plus P-50iB Startup Guide", "MARGUP50I07201E_REV_A/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "ZDT Startup Guide Set (IR809 Data Collector)", "SERGGI80902181E_REV_A/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "ZDT Startup Guide Set (VM Data Collector)", "SERGGIVMA03181E_REV_D/book.pdf"))
    Level2_Desc = insFld(Level1_Desc, gFld("R-30iB Mini Plus"))
      Level3_Desc = insFld(Level2_Desc, gFld("CRX-10iA, CRX-10iA/L"))
        insDoc(Level3_Desc, gLnk("B", "CRX-10iA Startup Guide", "MARGGCRXR07201E_REV_B/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Mechanical Unit Operator", "B-84194EN_REV_01/book.pdf"))
      Level3_Desc = insFld(Level2_Desc, gFld("Sensor Mechanical Unit/Control Unit"))
        insDoc(Level3_Desc, gLnk("B", "Sensor Mechanical Unit/Control Unit Operator", "B-83984EN_REV_03/book.pdf"))
    Level2_Desc = insFld(Level1_Desc, gFld("R-30iB Plus"))
      Level3_Desc = insFld(Level2_Desc, gFld("ARC Mate 100iC/12, M-10iA/12, /7L, /12S, /8L"))
        insDoc(Level3_Desc, gLnk("B", "/12, /7L, /12S, /8L Mechanical Unit Operator", "B-83654EN_REV_06/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "ARC Mate 100iC/M-10iA, 100iD/M-10iD Startup Guide", "MARGUM10A04171E_REV_D/book.pdf"))
      Level3_Desc = insFld(Level2_Desc, gFld("ARC Mate 100iC/M-10iA, 100iD/M-10iD"))
        insDoc(Level3_Desc, gLnk("B", "/e, /6L, /10S, /10M, /10MS Mechanical Unit Operator", "MAROCAM1010071E_REV_P/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "ARC Mate 100iC/M-10iA, 100iD/M-10iD Startup Guide", "MARGUM10A04171E_REV_D/book.pdf"))
      Level3_Desc = insFld(Level2_Desc, gFld("ARC Mate 100iD/M-10iD"))
        insDoc(Level3_Desc, gLnk("B", "ARC Mate 100iC/M-10iA, 100iD/M-10iD Startup Guide", "MARGUM10A04171E_REV_D/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Mechanical Unit Operator", "B-83944EN_REV_04/book.pdf"))
      Level3_Desc = insFld(Level2_Desc, gFld("ARC Mate 120iC/20T, M-20iA/20T"))
        insDoc(Level3_Desc, gLnk("B", "/20T, /20MT, /35MT Mechanical Unit Operator", "MAROCA20T07091E_REV_H/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "ARC Mate 100iC/M-10iA, 100iD/M-10iD Startup Guide", "MARGUM10A04171E_REV_D/book.pdf"))
      Level3_Desc = insFld(Level2_Desc, gFld("ARC Mate 120iC/M-20iA"))
        insDoc(Level3_Desc, gLnk("B", "/10L, /20M, /12L, /35M Mechanical Unit Operator", "B-82874EN_REV_13/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "ARC Mate 100iC/M-10iA, 100iD/M-10iD Startup Guide", "MARGUM10A04171E_REV_D/book.pdf"))
      Level3_Desc = insFld(Level2_Desc, gFld("ARC Mate 120iD/M-20iD"))
        insDoc(Level3_Desc, gLnk("B", "ARC Mate 100iC/M-10iA, 100iD/M-10iD Startup Guide", "MARGUM10A04171E_REV_D/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Mechanical Unit Operator", "B-84074EN_REV_04/book.pdf"))
      Level3_Desc = insFld(Level2_Desc, gFld("Arc Welding Power Supply"))
        insDoc(Level3_Desc, gLnk("B", "Daihen Digital Operators", "MAROBDWLD10151E_REV_A/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "FRONIUS TPS/i Welding Power Supply", "MAROWFTPS12181E_REV_A/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Miller Weld Equipment Library Option", "MAROBMWLD02131E_REV_D/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "SKS Weld Equipment Library Option", "MAROBSKSW02151E_REV_C/book.pdf"))
      Level3_Desc = insFld(Level2_Desc, gFld("CR-15iA"))
        insDoc(Level3_Desc, gLnk("B", "CR-15iA Startup Guide", "MARGUCR1507191E_REV_B/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Hand Guidance Operator", "MAROBHNGD05171E_REV_B/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Mechanical Unit Operator", "MARAUCR1509181E_REV_A/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Small Hand Guidance Operator", "MAROBSHGD02191E_REV_A/book.pdf"))
      Level3_Desc = insFld(Level2_Desc, gFld("CR-35iA"))
        insDoc(Level3_Desc, gLnk("B", "CR-35iA Startup Guide", "MARGUCR3504171E_REV_C/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Hand Guidance Operator", "MAROBHNGD05171E_REV_B/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Mechanical Unit Operator", "MAROBCR3509151E_REV_B/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Small Hand Guidance Operator", "MAROBSHGD02191E_REV_A/book.pdf"))
      Level3_Desc = insFld(Level2_Desc, gFld("DR-3iB"))
        insDoc(Level3_Desc, gLnk("B", "DR-3iB Startup Guide", "MARGUDR3I04211E_REV_A/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Mechanical Unit Operator", "B-84114EN_REV_01/book.pdf"))
      Level3_Desc = insFld(Level2_Desc, gFld("Gen II and Gen III Overslung Rail"))
        insDoc(Level3_Desc, gLnk("B", "Gen II and Gen III Overslung Rail Operator", "MAROPOSR302201E_REV_A/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Gen II Over Slung Rail Installation", "MARXCG2OR07151E_REV_B/book.pdf"))
      Level3_Desc = insFld(Level2_Desc, gFld("M-2000iA /1200, /900L, /2300, /1700L"))
        insDoc(Level3_Desc, gLnk("B", "General Robot Startup Guide", "MARGGGPSG08171E_REV_B/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Mechanical Unit Operator", "B-83014EN_REV_09/book.pdf"))
      Level3_Desc = insFld(Level2_Desc, gFld("M-20iB"))
        insDoc(Level3_Desc, gLnk("B", "/25/35S/25C Mechanical Unit Operator", "MAROBM22503161E_REV_C/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "M-20iB Startup Guide", "MARGUM2IB04171E_REV_C/book.pdf"))
      Level3_Desc = insFld(Level2_Desc, gFld("M-2iA"))
        insDoc(Level3_Desc, gLnk("B", "/3S, /3SL, /6H, /6HL, /3A, /3AL Mechanical Unit Operator", "MAROBM2IA01131E_REV_E/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "M-2iA/M-3iA Series Startup Guide", "MARGUM2M306171E_REV_B/book.pdf"))
      Level3_Desc = insFld(Level2_Desc, gFld("M-3iA"))
        insDoc(Level3_Desc, gLnk("B", "/6S, /6A, /12H Mechanical Unit Operator", "MAROCM3IA05101E_REV_F/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "M-2iA/M-3iA Series Startup Guide", "MARGUM2M306171E_REV_B/book.pdf"))
      Level3_Desc = insFld(Level2_Desc, gFld("M-410iB/140H"))
        insDoc(Level3_Desc, gLnk("B", "General Robot Startup Guide", "MARGGGPSG08171E_REV_B/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Mechanical Unit Operator", "MAROCM40H05101E_REV_D/book.pdf"))
      Level3_Desc = insFld(Level2_Desc, gFld("M-410iB/700"))
        insDoc(Level3_Desc, gLnk("B", "General Robot Startup Guide", "MARGGGPSG08171E_REV_B/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Mechanical Unit Operator", "MAROC410708081E_REV_E/book.pdf"))
      Level3_Desc = insFld(Level2_Desc, gFld("M-410iC"))
        insDoc(Level3_Desc, gLnk("B", "/110, /185, /315, /500 Mechanical Unit Operator", "B-83584EN_REV_07/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "General Robot Startup Guide", "MARGGGPSG08171E_REV_B/book.pdf"))
      Level3_Desc = insFld(Level2_Desc, gFld("M-710iC"))
        insDoc(Level3_Desc, gLnk("B", "/50, /70, /50H, /50S, /45M, /50E Mechanical Unit Operator", "MARAC710C02061E_REV_L/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "General Robot Startup Guide", "MARGGGPSG08171E_REV_B/book.pdf"))
      Level3_Desc = insFld(Level2_Desc, gFld("M-710iC/20L, /12L, /20M"))
        insDoc(Level3_Desc, gLnk("B", "General Robot Startup Guide", "MARGGGPSG08171E_REV_B/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "M-710iC/20L, /12L, 20M Mechanical Unit Operator", "MAROCM71009061E_REV_I/book.pdf"))
      Level3_Desc = insFld(Level2_Desc, gFld("M-710iC/50T"))
        insDoc(Level3_Desc, gLnk("B", "General Robot Startup Guide", "MARGGGPSG08171E_REV_B/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "M-710iC/50T, M-710iC/70T Mechanical Unit Operator", "MAROCM71T11061E_REV_F/book.pdf"))
      Level3_Desc = insFld(Level2_Desc, gFld("M-710iC/70T"))
        insDoc(Level3_Desc, gLnk("B", "General Robot Startup Guide", "MARGGGPSG08171E_REV_B/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "M-710iC/50T, M-710iC/70T Mechanical Unit Operator", "MAROCM71T11061E_REV_F/book.pdf"))
      Level3_Desc = insFld(Level2_Desc, gFld("M-800iA"))
        insDoc(Level3_Desc, gLnk("B", "General Robot Startup Guide", "MARGGGPSG08171E_REV_B/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Mechanical Unit Operator", "B-84204EN_REV_01/book.pdf"))
      Level3_Desc = insFld(Level2_Desc, gFld("M-900iB/360/280L/280/330L"))
        insDoc(Level3_Desc, gLnk("B", "/360, /280L, /280, /330L Mechanical Unit Operator", "B-83684EN_REV_05/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "General Robot Startup Guide", "MARGGGPSG08171E_REV_B/book.pdf"))
      Level3_Desc = insFld(Level2_Desc, gFld("M-900iB/700, 400L"))
        insDoc(Level3_Desc, gLnk("B", "/700, /400L Mechanical Unit Operator", "MAROBM97009121E_REV_D/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "General Robot Startup Guide", "MARGGGPSG08171E_REV_B/book.pdf"))
      Level3_Desc = insFld(Level2_Desc, gFld("P-1000iA"))
        insDoc(Level3_Desc, gLnk("B", "Mechanical Unit Operator", "MAROBP10007131E_REV_D/book.pdf"))
      Level3_Desc = insFld(Level2_Desc, gFld("P-20iB and P-25iB"))
        insDoc(Level3_Desc, gLnk("B", "Mechanical Unit Operator", "MAROB25IB05161E_REV_A/book.pdf"))
      Level3_Desc = insFld(Level2_Desc, gFld("P-250iB"))
        insDoc(Level3_Desc, gLnk("B", "Mechanical Unit Operator", "MAROB25IB07151E_REV_C/book.pdf"))
      Level3_Desc = insFld(Level2_Desc, gFld("P-350iA/45"))
        insDoc(Level3_Desc, gLnk("B", "Mechanical Unit Operator", "MAROBP35006151E_REV_E/book.pdf"))
      Level3_Desc = insFld(Level2_Desc, gFld("P-35iA"))
        insDoc(Level3_Desc, gLnk("B", "Mechanical Unit Operator", "MAROBP35A06141E_REV_B/book.pdf"))
      Level3_Desc = insFld(Level2_Desc, gFld("P-700iB"))
        insDoc(Level3_Desc, gLnk("B", "General Paint Process Engineering Guidelines", "MARMGPROC08171E_REV_A/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "General Paint Product Engineering Guidelines", "MARMGPDCT08171E_REV_A/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Mechanical Unit Operator", "MAROBP7IB04161E_REV_D/book.pdf"))
      Level3_Desc = insFld(Level2_Desc, gFld("Purged Enclosures"))
        insDoc(Level3_Desc, gLnk("B", "Purged Enclosure/Purged Motor Box Operator", "MAROBPPEB03201E_REV_A/book.pdf"))
      Level3_Desc = insFld(Level2_Desc, gFld("R-1000iA"))
        insDoc(Level3_Desc, gLnk("B", "General Robot Startup Guide", "MARGGGPSG08171E_REV_B/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Mechanical Unit Operator", "B-83004EN_REV_09/book.pdf"))
      Level3_Desc = insFld(Level2_Desc, gFld("R-2000iB"))
        insDoc(Level3_Desc, gLnk("B", "General Robot Startup Guide", "MARGGGPSG08171E_REV_B/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Mechanical Unit Operator", "MAROC200B05061E_REV_K/book.pdf"))
      Level3_Desc = insFld(Level2_Desc, gFld("R-2000iB/200T"))
        insDoc(Level3_Desc, gLnk("B", "General Robot Startup Guide", "MARGGGPSG08171E_REV_B/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Mechanical Unit Maintenance", "MARMC200T02071E_REV_F/book.pdf"))
      Level3_Desc = insFld(Level2_Desc, gFld("R-2000iC"))
        insDoc(Level3_Desc, gLnk("B", "Mechanical Unit Operator", "B-83644EN_REV_07/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "R-2000iC/R-2000iD Startup Guide", "MARGUR2IC10161E_REV_C/book.pdf"))
      Level3_Desc = insFld(Level2_Desc, gFld("R-2000iC/210WE"))
        insDoc(Level3_Desc, gLnk("B", "Mechanical Unit Operator", "B-84014EN_REV_02/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "R-2000iC/R-2000iD Startup Guide", "MARGUR2IC10161E_REV_C/book.pdf"))
      Level3_Desc = insFld(Level2_Desc, gFld("R-2000iD"))
        insDoc(Level3_Desc, gLnk("B", "Mechanical Unit Operator", "B-84124EN_REV_02/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "R-2000iC/R-2000iD Startup Guide", "MARGUR2IC10161E_REV_C/book.pdf"))
      Level3_Desc = insFld(Level2_Desc, gFld("Robot Transfer Unit"))
        insDoc(Level3_Desc, gLnk("B", "RTU Operator", "MAROGRTU203181E_REV_A/book.pdf"))
      Level3_Desc = insFld(Level2_Desc, gFld("Sensor Mechanical Unit/Control Unit"))
        insDoc(Level3_Desc, gLnk("B", "Sensor Mechanical Unit/Control Unit Operator", "B-83984EN_REV_03/book.pdf"))
      Level3_Desc = insFld(Level2_Desc, gFld("Servo Positioner"))
        insDoc(Level3_Desc, gLnk("B", "1-Axis Servo Positioner Mechanical Operator", "B-84154EN_REV_01/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "2-axis Servo Positioner Operator", "B-82534EN_REV_01/book.pdf"))
      Level3_Desc = insFld(Level2_Desc, gFld("Startup Guide"))
        insDoc(Level3_Desc, gLnk("B", "ARC Mate 100iC/M-10iA, 100iD/M-10iD Startup Guide", "MARGUM10A04171E_REV_D/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "CR-15iA Startup Guide", "MARGUCR1507191E_REV_B/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "CR-35iA Startup Guide", "MARGUCR3504171E_REV_C/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "DR-3iB Startup Guide", "MARGUDR3I04211E_REV_A/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "General Robot Startup Guide", "MARGGGPSG08171E_REV_B/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "M-20iB Startup Guide", "MARGUM2IB04171E_REV_C/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "M-2iA/M-3iA Series Startup Guide", "MARGUM2M306171E_REV_B/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "R-2000iC/R-2000iD Startup Guide", "MARGUR2IC10161E_REV_C/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "ZDT Startup Guide Set (IR809 Data Collector)", "SERGGI80902181E_REV_A/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "ZDT Startup Guide Set (VM Data Collector)", "SERGGIVMA03181E_REV_D/book.pdf"))
  Level1_Desc = insFld(foldersTree, gFld("Software Manuals"))
    Level2_Desc = insFld(Level1_Desc, gFld("_Safety"))
      Level3_Desc = insFld(Level2_Desc, gFld("Safety Handbook"))
        insDoc(Level3_Desc, gLnk("B", "Safety Handbook", "B-80687EN_REV_17/book.pdf"))
    Level2_Desc = insFld(Level1_Desc, gFld("V9.10 (R-30iB Compact Plus/SCARA)"))
      Level3_Desc = insFld(Level2_Desc, gFld("Communications"))
        insDoc(Level3_Desc, gLnk("B", "CC-Link Interface (Slave) Operator", "MAROCUCCLK0817E_REV_A/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "DeviceNet Setup and Operations", "MAROC75DV07091E_REV_D/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "EtherNet Global Data Setup and Operations", "MAROCEGDA08051E_REV_F/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "EtherNet/IP Setup and Operations", "MAROU91EN02171E_REV_C/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "HMI Device Communication (GE Series 90 SNPX) Operator", "MARUCHMID06121E_REV_B/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Internet Options Setup and Operations Manual", "MAROUIN9010171E_REV_H/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Profibus-DP (12M) Operator", "MAROCPRDP04071E_REV_C/book.pdf"))
      Level3_Desc = insFld(Level2_Desc, gFld("Operations"))
        insDoc(Level3_Desc, gLnk("B", "HandlingTool Setup and Operations", "MAROUHT9102171E_REV_G/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "iRPickTool Operators Manual", "B-83924EN_REV_02/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Software Installation Manual", "MARFUINS912171E_REV_D/book.pdf"))
      Level3_Desc = insFld(Level2_Desc, gFld("Options"))
        insDoc(Level3_Desc, gLnk("B", "Basic Interference Check & Intelligent Interference Check", "MAROBBI8204121E_REV_F/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Dual Check Safety Function Operator", "B-83184EN_REV_11/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "External Machine Vision Interface Operator", "B-84244_REV_01/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "iRCalibration Operator (V8.30 and later)", "B-83724EN_REV_03/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "iRVision 2D Camera Application Operator", "B-83914EN-2_REV_02/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "iRVision 3DV Sensor Operator", "B-83914EN-3_REV_02/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "iRVision Bin Picking Application Operator", "B-83914EN-6_REV_02/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "iRVision Error Handling Setup and Operations", "MAROCIERH02131E_REV_B/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "iRVision Inspection Application Operator", "B-83914EN-5_REV_02/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "iRVision Operator", "B-83914EN-1_REV_04/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Line Tracking Setup and Operations", "MAROULNTK01171E_REV_D/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "MTConnect Adapter Operator", "B-84254EN_REV_01/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "PLC Motion I/O Interface Manual", "B-84214EN_REV_01/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Remote Motion Interface", "MAROGRMIM11191E_REV_B/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "ZDT GI Data Collector Users Guide", "MAROBZGID11171E_REV_A/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "ZDT Operator (Combined User and Data Collector Guide)", "MARUGZDTA10191E_REV_B/book.pdf"))
      Level3_Desc = insFld(Level2_Desc, gFld("Reference"))
        insDoc(Level3_Desc, gLnk("B", "Error Code Manual", "MARRUEROR02171E_REV_I/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "iPendant Customization Guide", "MARRUCSTO02171E_REV_C/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "KAREL Reference", "MARRC75KR07091E_REV_L/book.pdf"))
      Level3_Desc = insFld(Level2_Desc, gFld("Startup Guide"))
        insDoc(Level3_Desc, gLnk("B", "SR-3iA/SR-6iA Startup Guide (Software Version 9.10P/07)", "MARGUSR3601181E_REV_B/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "SR-3iA/SR-6iA Startup Guide (Software Version 9.10P/09)", "MARGXSR3605181E_REV_A/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "SR-3iA/SR-6iA/SR-12iA Startup Guide (Software Version 9.10P/10 and later)", "MARGXSR3606181E_REV_E/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "ZDT Startup Guide Set (IR809 Data Collector)", "SERGGI80902181E_REV_A/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "ZDT Startup Guide Set (VM Data Collector)", "SERGGIVMA03181E_REV_D/book.pdf"))
    Level2_Desc = insFld(Level1_Desc, gFld("V9.10 (R-30iB Mate Plus)"))
      Level3_Desc = insFld(Level2_Desc, gFld("Communications"))
        insDoc(Level3_Desc, gLnk("B", "CC-Link IE Field Communication Function Operator", "MAROCCCIE09141E_REV_B/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "CC-Link Interface (Slave) Operator", "MAROCUCCLK0817E_REV_A/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Data Transfer Function Operator", "MAROJDTFO06801E_REV_A/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "DeviceNet Setup and Operations", "MAROC75DV07091E_REV_D/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "EtherCAT Function Operator", "MAROBECAT06141E_REV_B/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "EtherNet Global Data Setup and Operations", "MAROCEGDA08051E_REV_F/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "EtherNet/IP Setup and Operations", "MAROU91EN02171E_REV_C/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "FL-Net Interface Operator", "MAROBFLNT10121E_REV_D/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "HMI Device Communication (GE Series 90 SNPX) Operator", "MARUCHMID06121E_REV_B/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "HMI Device Communication (with OPC UA or MODBUS/TCP) Operator", "MARUCHOPM05191E_REV_A/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Internet Options Setup and Operations Manual", "MAROUIN9010171E_REV_H/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Modbus TCP Interface Setup and Operations", "MAROCMODB06071E_REV_C/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Molex Dual Channel ProfiNET Setup and Operations", "MAROBDCPN01141E_REV_F/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Profibus-DP (12M) Operator", "MAROCPRDP04071E_REV_C/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "ProfiNet Operator", "B-82864EN_REV_06/book.pdf"))
      Level3_Desc = insFld(Level2_Desc, gFld("Operations"))
        insDoc(Level3_Desc, gLnk("B", "ArcTool Setup and Operations", "MAROUAR9102171E_REV_G/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "HandlingTool Setup and Operations", "MAROUHT9102171E_REV_G/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "iRPickTool (Auto Visual Track Frame Setup)", "MARGGPTVT11171E_REV_A/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "iRPickTool Operators Manual", "B-83924EN_REV_02/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "PaintTool Setup and Operations", "MAROUPT9102171E_REV_A/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Software Installation Manual", "MARFUINS912171E_REV_D/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Software Installation Startup Guide", "MARGTSI8301161E_REV_C/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "SpotTool+ Setup and Operations", "MAROUST9102171E_REV_G/book.pdf"))
      Level3_Desc = insFld(Level2_Desc, gFld("Options"))
        insDoc(Level3_Desc, gLnk("B", "Basic Interference Check & Intelligent Interference Check", "MAROBBI8204121E_REV_F/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Collaborative Robot Function Operator", "B-83744EN_REV_04/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Dual Check Safety Function Operator", "B-83184EN_REV_11/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "External Machine Vision Interface Operator", "B-84244_REV_01/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Force Control Deburring Package Operators", "B-83934EN-1_REV_02/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Force Sensor Operator", "MAROUFSEN11171E_REV_A/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Initial Setup Function Operator", "MAROCINSE06091E_REV_D/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Integrated PMC Operator", "B-83254EN_REV_03/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "iRCalibration Operator (V8.30 and later)", "B-83724EN_REV_03/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "iRTorchMate Setup and Operations", "MAROURTCH05181E_REV_A/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "iRVision 2D Camera Application Operator", "B-83914EN-2_REV_02/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "iRVision 3D laser Vision Sensor Application Operator", "B-83914EN-4_REV_02/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "iRVision 3DV Sensor Operator", "B-83914EN-3_REV_02/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "iRVision Bin Picking Application Operator", "B-83914EN-6_REV_02/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "iRVision Error Handling Setup and Operations", "MAROCIERH02131E_REV_B/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "iRVision Inspection Application Operator", "B-83914EN-5_REV_02/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "iRVision Operator", "B-83914EN-1_REV_04/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "KAREL and TPP Program Diagnostic Option", "MARACTPPD03081E_REV_D/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Laser Process Control Function Operators Manual", "MARUULPRC08181E_REV_B/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Line Tracking Setup and Operations", "MAROULNTK01171E_REV_D/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Machine Tool Easy Setup Operator", "MAROBMTES09121E_REV_C/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "MTConnect Adapter Operator", "B-84254EN_REV_01/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "NC Program Conversion User Guide", "MARUCNCPR06121E_REV_D/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "PLC Motion I/O Interface Manual", "B-84214EN_REV_01/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "PLC Motion Interface Manual", "MARUGPLCR01181E_REV_B/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Remote Motion Interface", "MAROGRMIM11191E_REV_B/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Robot and Machine Tool Function", "MAROCMTOL08091E_REV_D/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Spot Easy Normal Operators Manual", "MAROBENOR11121E_REV_D/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "System Design Tool Operator", "MAROBDSGN07121E_REV_B/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "ZDT GI Data Collector Users Guide", "MAROBZGID11171E_REV_A/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "ZDT Operator (Combined User and Data Collector Guide)", "MARUGZDTA10191E_REV_B/book.pdf"))
      Level3_Desc = insFld(Level2_Desc, gFld("Reference"))
        insDoc(Level3_Desc, gLnk("B", "Error Code Manual", "MARRUEROR02171E_REV_I/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "iPendant Customization Guide", "MARRUCSTO02171E_REV_C/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "KAREL Reference", "MARRC75KR07091E_REV_L/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "R-30iB to R-30iB Plus Compatibility Guide", "MAROUCPAT01171E_REV_C/book.pdf"))
      Level3_Desc = insFld(Level2_Desc, gFld("Startup Guide"))
        insDoc(Level3_Desc, gLnk("B", "Software Installation Startup Guide", "MARGTSI8301161E_REV_C/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "ZDT Startup Guide Set (IR809 Data Collector)", "SERGGI80902181E_REV_A/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "ZDT Startup Guide Set (VM Data Collector)", "SERGGIVMA03181E_REV_D/book.pdf"))
    Level2_Desc = insFld(Level1_Desc, gFld("V9.10 (R-30iB Plus)"))
      Level3_Desc = insFld(Level2_Desc, gFld("Communications"))
        insDoc(Level3_Desc, gLnk("B", "CC-Link IE Field Communication Function Operator", "MAROCCCIE09141E_REV_B/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "CC-Link Interface (Slave) Operator", "MAROCUCCLK0817E_REV_A/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Data Transfer Function Operator", "MAROJDTFO06801E_REV_A/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "DeviceNet Setup and Operations", "MAROC75DV07091E_REV_D/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "EtherCAT Function Operator", "MAROBECAT06141E_REV_B/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "EtherNet Global Data Setup and Operations", "MAROCEGDA08051E_REV_F/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "EtherNet/IP Setup and Operations", "MAROU91EN02171E_REV_C/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "FL-Net Interface Operator", "MAROBFLNT10121E_REV_D/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "HMI Device Communication (GE Series 90 SNPX) Operator", "MARUCHMID06121E_REV_B/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "HMI Device Communication (with OPC UA or MODBUS/TCP) Operator", "MARUCHOPM05191E_REV_A/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Interbus Function for Phoenix Contact PCI Board Operator", "MAROCIBPX04071E_REV_C/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Internet Options Setup and Operations Manual", "MAROUIN9010171E_REV_H/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Modbus TCP Interface Setup and Operations", "MAROCMODB06071E_REV_C/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Molex Dual Channel ProfiNET Setup and Operations", "MAROBDCPN01141E_REV_F/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Profibus-DP (12M) Operator", "MAROCPRDP04071E_REV_C/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "ProfiNet Operator", "B-82864EN_REV_06/book.pdf"))
      Level3_Desc = insFld(Level2_Desc, gFld("Operations"))
        insDoc(Level3_Desc, gLnk("B", "ArcTool Setup and Operations", "MAROUAR9102171E_REV_G/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "HandlingTool Setup and Operations", "MAROUHT9102171E_REV_G/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "iRPickTool (Auto Visual Track Frame Setup)", "MARGGPTVT11171E_REV_A/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "iRPickTool Operators Manual", "B-83924EN_REV_02/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "PaintTool Setup and Operations", "MAROUPT9102171E_REV_A/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "PalletTool Setup and Operations", "MAROUPLT902171E_REV_B/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "RemovalTool Setup and Operations", "MAROCRMVL07061E_REV_D/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Software Installation Manual", "MARFUINS912171E_REV_D/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Software Installation Startup Guide", "MARGTSI8301161E_REV_C/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "SpotTool+ Setup and Operations", "MAROUST9102171E_REV_G/book.pdf"))
      Level3_Desc = insFld(Level2_Desc, gFld("Options"))
        insDoc(Level3_Desc, gLnk("B", "Basic Interference Check & Intelligent Interference Check", "MAROBBI8204121E_REV_F/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "CD Stationary Track & RPM Clock Users Guide", "MARUBCSTK03151E_REV_C/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Collaborative Robot Function Operator", "B-83744EN_REV_04/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Coordinated Motion Setup and Operations", "MAROB81CM04081E_REV_E/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Dual Check Safety Function Operator", "B-83184EN_REV_11/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Dynamic Path Modification Users Guide", "MARUBDPMO02141E_REV_B/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "External Machine Vision Interface Operator", "B-84244_REV_01/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Force Control Deburring Package Operators", "B-83934EN-1_REV_02/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Force Sensor Operator", "MAROUFSEN11171E_REV_A/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Genkotsu Learning Control (V8.30 and later)", "MAROUGLCF07171E_REV_B/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Hand Guidance Operator", "MAROBHNGD05171E_REV_B/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Initial Setup Function Operator", "MAROCINSE06091E_REV_D/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Integrated PMC Operator", "B-83254EN_REV_03/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Integrated Welding Control Interface Operator (Dengensha Spec)", "MAROCDENG04071E_REV_D/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Integrated Welding Control Interface Operator (WTC/Medar)", "MAROCWTCM04071E_REV_C/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "iRCalibration Operator (V8.30 and later)", "B-83724EN_REV_03/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "iRDiagnostics Operations", "MAROBDG8204121E_REV_E/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "iRTorchMate Setup and Operations", "MAROURTCH05181E_REV_A/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "iRVision 2D Camera Application Operator", "B-83914EN-2_REV_02/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "iRVision 3D laser Vision Sensor Application Operator", "B-83914EN-4_REV_02/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "iRVision 3DV Sensor Operator", "B-83914EN-3_REV_02/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "iRVision Bin Picking Application Operator", "B-83914EN-6_REV_02/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "iRVision Error Handling Setup and Operations", "MAROCIERH02131E_REV_B/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "iRVision Inspection Application Operator", "B-83914EN-5_REV_02/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "iRVision Operator", "B-83914EN-1_REV_04/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "KAREL and TPP Program Diagnostic Option", "MARACTPPD03081E_REV_D/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Laser Process Control Function Operators Manual", "MARUULPRC08181E_REV_B/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Learning Path Control Operator", "MAROBLPCN02141E_REV_B/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Learning Robot Operator Manual", "B-83534EN_REV_06/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Line Tracking Setup and Operations", "MAROULNTK01171E_REV_D/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Machine Tool Easy Setup Operator", "MAROBMTES09121E_REV_C/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Miller Weld Equipment Library Option", "MAROBMWLD02131E_REV_D/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "MTConnect Adapter Operator", "B-84254EN_REV_01/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "MultiArm Controller Option", "MAROBMA8203131E_REV_B/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "NC Program Conversion User Guide", "MARUCNCPR06121E_REV_D/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "PLC Motion I/O Interface Manual", "B-84214EN_REV_01/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "PLC Motion Interface Manual", "MARUGPLCR01181E_REV_B/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Pressure Control Function Users Guide", "MARUBFLPC06141E_REV_B/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Process Logger Setup and Operations", "MAROBPLOG04121E_REV_C/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Rail Zone Users Guide", "MAROBRZNE02121E_REV_F/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Remote Motion Interface", "MAROGRMIM11191E_REV_B/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Robot and Machine Tool Function", "MAROCMTOL08091E_REV_D/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Servo Gun Function Operator", "MAROBSGUN05121E_REV_E/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Servo Gun Tip Wear Users Guide", "MARUBSGTD09131E_REV_B/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Servo Torch for ARC Mate iC series (Option) Operator", "B-83074EN_REV_05/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Servo Torch Installation and Setup", "MARFISVTC11021E_REV_F/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "SKS Weld Equipment Library Option", "MAROBSKSW02151E_REV_C/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "SPI Interface Setup and Operations", "MAROISPIN12041E_REV_D/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Spot Easy Normal Operators Manual", "MAROBENOR11121E_REV_D/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "System Design Tool Operator", "MAROBDSGN07121E_REV_B/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "ZDT (On-Premise) Operator", "B-84064EN_REV_04/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "ZDT GI Data Collector Users Guide", "MAROBZGID11171E_REV_A/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "ZDT Operator (Combined User and Data Collector Guide)", "MARUGZDTA10191E_REV_B/book.pdf"))
      Level3_Desc = insFld(Level2_Desc, gFld("Reference"))
        insDoc(Level3_Desc, gLnk("B", "Error Code Manual", "MARRUEROR02171E_REV_I/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "iPendant Customization Guide", "MARRUCSTO02171E_REV_C/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "KAREL Reference", "MARRC75KR07091E_REV_L/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "R-30iB to R-30iB Plus Compatibility Guide", "MAROUCPAT01171E_REV_C/book.pdf"))
      Level3_Desc = insFld(Level2_Desc, gFld("Startup Guide"))
        insDoc(Level3_Desc, gLnk("B", "Software Installation Startup Guide", "MARGTSI8301161E_REV_C/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "ZDT Startup Guide Set (IR809 Data Collector)", "SERGGI80902181E_REV_A/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "ZDT Startup Guide Set (VM Data Collector)", "SERGGIVMA03181E_REV_D/book.pdf"))
    Level2_Desc = insFld(Level1_Desc, gFld("V9.30 (R-30iB Compact Plus/SCARA)"))
      Level3_Desc = insFld(Level2_Desc, gFld("Communications"))
        insDoc(Level3_Desc, gLnk("B", "CC-Link Interface (Slave) Operator", "MAROCUCCLK0817E_REV_A/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "DeviceNet Setup and Operations", "MAROC75DV07091E_REV_D/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "EtherNet Global Data Setup and Operations", "MAROCEGDA08051E_REV_F/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "EtherNet/IP Setup and Operations", "MAROU91EN02171E_REV_C/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "HMI Device Communication (GE Series 90 SNPX) Operator", "MARUCHMID06121E_REV_B/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Internet Options Setup and Operations Manual", "MAROUIN9010171E_REV_H/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Profibus-DP (12M) Operator", "MAROCPRDP04071E_REV_C/book.pdf"))
      Level3_Desc = insFld(Level2_Desc, gFld("Operations"))
        insDoc(Level3_Desc, gLnk("B", "HandlingTool Setup and Operations", "MAROUHT9307191E_REV_C/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "iRPickTool Operators Manual", "B-83924EN_REV_02/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Software Installation Manual", "MARFUINS912171E_REV_D/book.pdf"))
      Level3_Desc = insFld(Level2_Desc, gFld("Options"))
        insDoc(Level3_Desc, gLnk("B", "Basic Interference Check & Intelligent Interference Check", "MAROBBI8204121E_REV_F/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Dual Check Safety Function Operator", "B-83184EN_REV_11/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "External Machine Vision Interface Operator", "B-84244_REV_01/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "iRCalibration Operator (V8.30 and later)", "B-83724EN_REV_03/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "iRVision 2D Camera Application Operator", "B-83914EN-2_REV_02/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "iRVision 3DV Sensor Operator", "B-83914EN-3_REV_02/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "iRVision Bin Picking Application Operator", "B-83914EN-6_REV_02/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "iRVision Error Handling Setup and Operations", "MAROCIERH02131E_REV_B/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "iRVision Inspection Application Operator", "B-83914EN-5_REV_02/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "iRVision Operator", "B-83914EN-1_REV_04/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Line Tracking Setup and Operations", "MAROULNTK01171E_REV_D/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "MTConnect Adapter Operator", "B-84254EN_REV_01/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "PLC Motion I/O Interface Manual", "B-84214EN_REV_01/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Remote Motion Interface", "MAROGRMIM11191E_REV_B/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "ZDT GI Data Collector Users Guide", "MAROBZGID11171E_REV_A/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "ZDT Operator (Combined User and Data Collector Guide)", "MARUGZDTA10191E_REV_B/book.pdf"))
      Level3_Desc = insFld(Level2_Desc, gFld("Reference"))
        insDoc(Level3_Desc, gLnk("B", "Error Code Manual", "MARRUEROR02171E_REV_I/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "iPendant Customization Guide", "MARUUIPCU02201E_REV_A/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "KAREL Reference", "MARRC75KR07091E_REV_L/book.pdf"))
      Level3_Desc = insFld(Level2_Desc, gFld("Startup Guide"))
        insDoc(Level3_Desc, gLnk("B", "SR-3iA/SR-6iA/SR-12iA Startup Guide (Software Version 9.10P/10 and later)", "MARGXSR3606181E_REV_E/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "ZDT Startup Guide Set (IR809 Data Collector)", "SERGGI80902181E_REV_A/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "ZDT Startup Guide Set (VM Data Collector)", "SERGGIVMA03181E_REV_D/book.pdf"))
    Level2_Desc = insFld(Level1_Desc, gFld("V9.30 (R-30iB Mate Plus)"))
      Level3_Desc = insFld(Level2_Desc, gFld("Communications"))
        insDoc(Level3_Desc, gLnk("B", "CC-Link IE Field Communication Function Operator", "MAROCCCIE09141E_REV_B/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "CC-Link Interface (Slave) Operator", "MAROCUCCLK0817E_REV_A/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Data Transfer Function Operator", "MAROJDTFO06801E_REV_A/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "DeviceNet Setup and Operations", "MAROC75DV07091E_REV_D/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "EtherCAT Function Operator", "MAROBECAT06141E_REV_B/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "EtherNet Global Data Setup and Operations", "MAROCEGDA08051E_REV_F/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "EtherNet/IP Setup and Operations", "MAROU91EN02171E_REV_C/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "FL-Net Interface Operator", "MAROBFLNT10121E_REV_D/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "HMI Device Communication (GE Series 90 SNPX) Operator", "MARUCHMID06121E_REV_B/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "HMI Device Communication (with OPC UA or MODBUS/TCP) Operator", "MARUCHOPM05191E_REV_A/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Internet Options Setup and Operations Manual", "MAROUIN9010171E_REV_H/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Modbus TCP Interface Setup and Operations", "MAROCMODB06071E_REV_C/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Molex Dual Channel ProfiNET Setup and Operations", "MAROBDCPN01141E_REV_F/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Profibus-DP (12M) Operator", "MAROCPRDP04071E_REV_C/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "ProfiNet Operator", "B-82864EN_REV_06/book.pdf"))
      Level3_Desc = insFld(Level2_Desc, gFld("Operations"))
        insDoc(Level3_Desc, gLnk("B", "ArcTool Setup and Operations", "MAROUAR9307191E_REV_C/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "HandlingTool Setup and Operations", "MAROUHT9307191E_REV_C/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "iRPickTool (Auto Visual Track Frame Setup)", "MARGGPTVT11171E_REV_A/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "iRPickTool Operators Manual", "B-83924EN_REV_02/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "PaintTool Setup and Operations", "MAROUPT9307191E_REV_A/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Software Installation Manual", "MARFUINS912171E_REV_D/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Software Installation Startup Guide", "MARGTSI8301161E_REV_C/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "SpotTool+ Setup and Operations", "MAROUST9307191E_REV_C/book.pdf"))
      Level3_Desc = insFld(Level2_Desc, gFld("Options"))
        insDoc(Level3_Desc, gLnk("B", "Basic Interference Check & Intelligent Interference Check", "MAROBBI8204121E_REV_F/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Collaborative Robot Function Operator", "B-83744EN_REV_04/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Dual Check Safety Function Operator", "B-83184EN_REV_11/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "External Machine Vision Interface Operator", "B-84244_REV_01/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Force Control Deburring Package Operators", "B-83934EN-1_REV_02/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Force Sensor Operator", "MAROUFSEN11171E_REV_A/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Initial Setup Function Operator", "MAROCINSE06091E_REV_D/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Integrated PMC Operator", "B-83254EN_REV_03/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "iRCalibration Operator (V8.30 and later)", "B-83724EN_REV_03/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "iRTorchMate Setup and Operations", "MAROURTCH05181E_REV_A/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "iRVision 2D Camera Application Operator", "B-83914EN-2_REV_02/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "iRVision 3D laser Vision Sensor Application Operator", "B-83914EN-4_REV_02/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "iRVision 3DV Sensor Operator", "B-83914EN-3_REV_02/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "iRVision Bin Picking Application Operator", "B-83914EN-6_REV_02/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "iRVision Error Handling Setup and Operations", "MAROCIERH02131E_REV_B/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "iRVision Inspection Application Operator", "B-83914EN-5_REV_02/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "iRVision Operator", "B-83914EN-1_REV_04/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "KAREL and TPP Program Diagnostic Option", "MARACTPPD03081E_REV_D/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Laser Process Control Function Operators Manual", "MARUULPRC08181E_REV_B/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Line Tracking Setup and Operations", "MAROULNTK01171E_REV_D/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Machine Tool Easy Setup Operator", "MAROBMTES09121E_REV_C/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "MTConnect Adapter Operator", "B-84254EN_REV_01/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "NC Program Conversion User Guide", "MARUCNCPR06121E_REV_D/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "PLC Motion I/O Interface Manual", "B-84214EN_REV_01/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "PLC Motion Interface Manual", "MARUGPLCR01181E_REV_B/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Remote Motion Interface", "MAROGRMIM11191E_REV_B/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Robot and Machine Tool Function", "MAROCMTOL08091E_REV_D/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Spot Easy Normal Operators Manual", "MAROBENOR11121E_REV_D/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "System Design Tool Operator", "MAROBDSGN07121E_REV_B/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "ZDT GI Data Collector Users Guide", "MAROBZGID11171E_REV_A/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "ZDT Operator (Combined User and Data Collector Guide)", "MARUGZDTA10191E_REV_B/book.pdf"))
      Level3_Desc = insFld(Level2_Desc, gFld("Reference"))
        insDoc(Level3_Desc, gLnk("B", "Error Code Manual", "MARRUEROR02171E_REV_I/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "iPendant Customization Guide", "MARUUIPCU02201E_REV_A/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "KAREL Reference", "MARRC75KR07091E_REV_L/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "R-30iB to R-30iB Plus Compatibility Guide", "MAROUCPAT01171E_REV_C/book.pdf"))
      Level3_Desc = insFld(Level2_Desc, gFld("Startup Guide"))
        insDoc(Level3_Desc, gLnk("B", "DR-3iB Startup Guide", "MARGUDR3I04211E_REV_A/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Software Installation Startup Guide", "MARGTSI8301161E_REV_C/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "ZDT Startup Guide Set (IR809 Data Collector)", "SERGGI80902181E_REV_A/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "ZDT Startup Guide Set (VM Data Collector)", "SERGGIVMA03181E_REV_D/book.pdf"))
    Level2_Desc = insFld(Level1_Desc, gFld("V9.30 (R-30iB Plus)"))
      Level3_Desc = insFld(Level2_Desc, gFld("Communications"))
        insDoc(Level3_Desc, gLnk("B", "CC-Link IE Field Communication Function Operator", "MAROCCCIE09141E_REV_B/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "CC-Link Interface (Slave) Operator", "MAROCUCCLK0817E_REV_A/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Data Transfer Function Operator", "MAROJDTFO06801E_REV_A/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "DeviceNet Setup and Operations", "MAROC75DV07091E_REV_D/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "EtherCAT Function Operator", "MAROBECAT06141E_REV_B/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "EtherNet Global Data Setup and Operations", "MAROCEGDA08051E_REV_F/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "EtherNet/IP Setup and Operations", "MAROU91EN02171E_REV_C/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "FL-Net Interface Operator", "MAROBFLNT10121E_REV_D/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "HMI Device Communication (GE Series 90 SNPX) Operator", "MARUCHMID06121E_REV_B/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "HMI Device Communication (with OPC UA or MODBUS/TCP) Operator", "MARUCHOPM05191E_REV_A/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Interbus Function for Phoenix Contact PCI Board Operator", "MAROCIBPX04071E_REV_C/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Internet Options Setup and Operations Manual", "MAROUIN9010171E_REV_H/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Modbus TCP Interface Setup and Operations", "MAROCMODB06071E_REV_C/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Molex Dual Channel ProfiNET Setup and Operations", "MAROBDCPN01141E_REV_F/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Profibus-DP (12M) Operator", "MAROCPRDP04071E_REV_C/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "ProfiNet Operator", "B-82864EN_REV_06/book.pdf"))
      Level3_Desc = insFld(Level2_Desc, gFld("Operations"))
        insDoc(Level3_Desc, gLnk("B", "ArcTool Setup and Operations", "MAROUAR9307191E_REV_C/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "HandlingTool Setup and Operations", "MAROUHT9307191E_REV_C/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "iRPickTool (Auto Visual Track Frame Setup)", "MARGGPTVT11171E_REV_A/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "iRPickTool Operators Manual", "B-83924EN_REV_02/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "PaintTool Setup and Operations", "MAROUPT9307191E_REV_A/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "PalletTool Setup and Operations", "MAROUPLT902171E_REV_B/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "RemovalTool Setup and Operations", "MAROCRMVL07061E_REV_D/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Software Installation Manual", "MARFUINS912171E_REV_D/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Software Installation Startup Guide", "MARGTSI8301161E_REV_C/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "SpotTool+ Setup and Operations", "MAROUST9307191E_REV_C/book.pdf"))
      Level3_Desc = insFld(Level2_Desc, gFld("Options"))
        insDoc(Level3_Desc, gLnk("B", "Basic Interference Check & Intelligent Interference Check", "MAROBBI8204121E_REV_F/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "CD Stationary Track & RPM Clock Users Guide", "MARUBCSTK03151E_REV_C/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Collaborative Robot Function Operator", "B-83744EN_REV_04/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Coordinated Motion Setup and Operations", "MAROB81CM04081E_REV_E/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Dual Check Safety Function Operator", "B-83184EN_REV_11/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Dynamic Path Modification Users Guide", "MARUBDPMO02141E_REV_B/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "External Machine Vision Interface Operator", "B-84244_REV_01/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Force Control Deburring Package Operators", "B-83934EN-1_REV_02/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Force Sensor Operator", "MAROUFSEN11171E_REV_A/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Genkotsu Learning Control (V8.30 and later)", "MAROUGLCF07171E_REV_B/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Hand Guidance Operator", "MAROBHNGD05171E_REV_B/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Initial Setup Function Operator", "MAROCINSE06091E_REV_D/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Integrated PMC Operator", "B-83254EN_REV_03/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Integrated Welding Control Interface Operator (Dengensha Spec)", "MAROCDENG04071E_REV_D/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Integrated Welding Control Interface Operator (WTC/Medar)", "MAROCWTCM04071E_REV_C/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "iRCalibration Operator (V8.30 and later)", "B-83724EN_REV_03/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "iRDiagnostics Operations", "MAROBDG8204121E_REV_E/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "iRTorchMate Setup and Operations", "MAROURTCH05181E_REV_A/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "iRVision 2D Camera Application Operator", "B-83914EN-2_REV_02/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "iRVision 3D laser Vision Sensor Application Operator", "B-83914EN-4_REV_02/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "iRVision 3DV Sensor Operator", "B-83914EN-3_REV_02/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "iRVision Bin Picking Application Operator", "B-83914EN-6_REV_02/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "iRVision Error Handling Setup and Operations", "MAROCIERH02131E_REV_B/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "iRVision Inspection Application Operator", "B-83914EN-5_REV_02/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "iRVision Operator", "B-83914EN-1_REV_04/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "KAREL and TPP Program Diagnostic Option", "MARACTPPD03081E_REV_D/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Laser Process Control Function Operators Manual", "MARUULPRC08181E_REV_B/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Learning Path Control Operator", "MAROBLPCN02141E_REV_B/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Learning Robot Operator Manual", "B-83534EN_REV_06/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Line Tracking Setup and Operations", "MAROULNTK01171E_REV_D/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Machine Tool Easy Setup Operator", "MAROBMTES09121E_REV_C/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "MTConnect Adapter Operator", "B-84254EN_REV_01/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "MultiArm Controller Option", "MAROBMA8203131E_REV_B/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "NC Program Conversion User Guide", "MARUCNCPR06121E_REV_D/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "PLC Motion I/O Interface Manual", "B-84214EN_REV_01/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "PLC Motion Interface Manual", "MARUGPLCR01181E_REV_B/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Pressure Control Function Users Guide", "MARUBFLPC06141E_REV_B/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Process Logger Setup and Operations", "MAROBPLOG04121E_REV_C/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Rail Zone Users Guide", "MAROBRZNE02121E_REV_F/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Remote Motion Interface", "MAROGRMIM11191E_REV_B/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Robot and Machine Tool Function", "MAROCMTOL08091E_REV_D/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Servo Gun Function Operator", "MAROBSGUN05121E_REV_E/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Servo Gun Tip Wear Users Guide", "MARUBSGTD09131E_REV_B/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Servo Torch for ARC Mate iC series (Option) Operator", "B-83074EN_REV_05/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Servo Torch Installation and Setup", "MARFISVTC11021E_REV_F/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "SKS Weld Equipment Library Option", "MAROBSKSW02151E_REV_C/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "SPI Interface Setup and Operations", "MAROISPIN12041E_REV_D/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Spot Easy Normal Operators Manual", "MAROBENOR11121E_REV_D/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "System Design Tool Operator", "MAROBDSGN07121E_REV_B/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "ZDT (On-Premise) Operator", "B-84064EN_REV_04/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "ZDT GI Data Collector Users Guide", "MAROBZGID11171E_REV_A/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "ZDT Operator (Combined User and Data Collector Guide)", "MARUGZDTA10191E_REV_B/book.pdf"))
      Level3_Desc = insFld(Level2_Desc, gFld("Reference"))
        insDoc(Level3_Desc, gLnk("B", "Error Code Manual", "MARRUEROR02171E_REV_I/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "iPendant Customization Guide", "MARUUIPCU02201E_REV_A/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "KAREL Reference", "MARRC75KR07091E_REV_L/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "R-30iB to R-30iB Plus Compatibility Guide", "MAROUCPAT01171E_REV_C/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "System Variable Addendum", "MARXUSVAR06181E_REV_A/book.pdf"))
      Level3_Desc = insFld(Level2_Desc, gFld("Startup Guide"))
        insDoc(Level3_Desc, gLnk("B", "DR-3iB Startup Guide", "MARGUDR3I04211E_REV_A/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Software Installation Startup Guide", "MARGTSI8301161E_REV_C/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "ZDT Startup Guide Set (IR809 Data Collector)", "SERGGI80902181E_REV_A/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "ZDT Startup Guide Set (VM Data Collector)", "SERGGIVMA03181E_REV_D/book.pdf"))
    Level2_Desc = insFld(Level1_Desc, gFld("V9.40 (R-30iB Mini Plus)"))
      Level3_Desc = insFld(Level2_Desc, gFld("Communications"))
        insDoc(Level3_Desc, gLnk("B", "CC-Link Interface (Slave) Operator", "MAROCUCCLK0817E_REV_A/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "EtherNet Global Data Setup and Operations", "MAROCEGDA08051E_REV_F/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "EtherNet/IP Setup and Operations", "MAROU91EN02171E_REV_C/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "FL-Net Interface Operator", "MAROBFLNT10121E_REV_D/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Internet Options Setup and Operations Manual", "MAROUIN9010171E_REV_H/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "ProfiNet Operator", "B-82864EN_REV_06/book.pdf"))
      Level3_Desc = insFld(Level2_Desc, gFld("Operations"))
        insDoc(Level3_Desc, gLnk("B", "Basic Function Operators", "B-83284EN_REV_09/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "iRPickTool Operators Manual", "B-83924EN_REV_02/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "PalletTool Setup and Operations", "MAROUPLT902171E_REV_B/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Tablet TP Operators Manual", "B-84274EN_REV_02/book.pdf"))
      Level3_Desc = insFld(Level2_Desc, gFld("Options"))
        insDoc(Level3_Desc, gLnk("B", "Collaborative Robot Function Operator", "B-83744EN_REV_04/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Dual Check Safety Function Operator", "B-83184EN_REV_11/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "External Machine Vision Interface Operator", "B-84244_REV_01/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "iRCalibration Operator (V8.30 and later)", "B-83724EN_REV_03/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "iRTorchMate Setup and Operations", "MAROURTCH05181E_REV_A/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "iRVision 2D Camera Application Operator", "B-83914EN-2_REV_02/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "iRVision 3D laser Vision Sensor Application Operator", "B-83914EN-4_REV_02/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "iRVision Error Handling Setup and Operations", "MAROCIERH02131E_REV_B/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "iRVision Operator", "B-83914EN-1_REV_04/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Line Tracking Setup and Operations", "MAROULNTK01171E_REV_D/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Modbus TCP Interface Setup and Operations", "MAROCMODB06071E_REV_C/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "MTConnect Adapter Operator", "B-84254EN_REV_01/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Optional Function Operators", "B-83284EN-2_REV_09/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "PLC Motion Interface Manual", "MARUGPLCR01181E_REV_B/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Remote Motion Interface", "MAROGRMIM11191E_REV_B/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "System Design Tool Operator", "MAROBDSGN07121E_REV_B/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "ZDT Operator (Combined User and Data Collector Guide)", "MARUGZDTA10191E_REV_B/book.pdf"))
      Level3_Desc = insFld(Level2_Desc, gFld("Reference"))
        insDoc(Level3_Desc, gLnk("B", "Error Code Manual", "MARRUEROR02171E_REV_I/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "KAREL Reference", "MARRC75KR07091E_REV_L/book.pdf"))
      Level3_Desc = insFld(Level2_Desc, gFld("Safety"))
        insDoc(Level3_Desc, gLnk("B", "Safety Handbook", "B-80687EN_REV_17/book.pdf"))
      Level3_Desc = insFld(Level2_Desc, gFld("Startup Guide"))
        insDoc(Level3_Desc, gLnk("B", "CRX-10iA Startup Guide", "MARGGCRXR07201E_REV_B/book.pdf"))
  Level1_Desc = insFld(foldersTree, gFld("TMR Manuals"))
    Level2_Desc = insFld(Level1_Desc, gFld("Technical Manual Reports"))
      Level3_Desc = insFld(Level2_Desc, gFld("Electrical"))
        insDoc(Level3_Desc, gLnk("B", "Restricted Use of Hazardous Substances", "B-83525EN071_REV_A/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Restricted Use of Hazardous Substances", "B-83555EN061_REV_A/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Symbol Operators Panel added", "B-83195EN091_REV_A/book.pdf"))
      Level3_Desc = insFld(Level2_Desc, gFld("Mechanical"))
        insDoc(Level3_Desc, gLnk("B", "Force Sensor Serial number term is added", "B-83734EN0102_REV_A/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Force Sensor Serial number term is added", "B-83774EN0201_REV_A/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Periodic Maintenance Table revised", "B-83734EN0101_REV_A/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Specification of the connectors correction", "B-82274EN1201_REV_A/book.pdf"))
      Level3_Desc = insFld(Level2_Desc, gFld("Software"))
        insDoc(Level3_Desc, gLnk("B", "Add description of Karel programs for iRVision OP manual", "TMR-B83304EN060101_REV_A/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Add descriptions for collaborative robot function", "TMR-B83744E0104_REV_A/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Addition of the description about 3DL Calibration tool enhancement", "TMR18004B83304EN0402_REV_A/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Alarm remedy change", "TMR-B8328410410_REV_A/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Collaborative - Add Push to Escape w/Variable Payload Comp and add Payload Identification", "TMR016B83744EN_REV_A/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Description is added", "B-82654EN0401_REV_A/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Hand Guidance for Standard Robot Operators Manual", "TMR20002E_REV_A/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "iRCalibration Operators Manual Additions", "TMR16052EB83724EN022_REV_A/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "QSSR for CNC and Robot", "A-42148E-022_REV_A/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Screen and small collaborative robot support added", "B-83744EN0103_REV_A/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Screen items, payload confirm, coll. robot monitor added", "B-83744EN0102_REV_A/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Servo Gun : Influence by the friction increase", "TMR02105EA75163_REV_A/book.pdf"))
        insDoc(Level3_Desc, gLnk("B", "Wireless accelerometer description added", "B-83534EN031_REV_A/book.pdf"))
insDoc(foldersTree, gLnk("B", "<Font size=1> &copy; FANUC America Corporation 1999-2021. All rights reserved. </Font>", "../policies/terms.htm"))
